Add padding to contour plot
optuna/optuna pull request #1716
Opened 2020-08-25 07:38 UTC by zchenry

## Motivation
As mentioned in https://github.com/optuna/optuna/issues/1697, it is difficult to see when points appear at the borders.

## Description of the changes
I checked available parameters of `plotly.graph_objects.Contour` but failed to find anything useful to introduce a padding. Although `plotly.graph_objects.Figure` has a `margin` parameter, it is used for the whole figure, not the plot(s) inside it.

To this end, I choose to use an empirical padding ratio of `0.05` (not sure if it is appropriate) and manually calculate the corresponding paddings.

Plot for the following code is attached.

```python
import optuna

def objective(trial):
    x = trial.suggest_float("x", 0, 1)
    y = trial.suggest_int("y", -1, 1)
    z = trial.suggest_loguniform("z", 1e-2, 1e3)
    return (x - 0.5) ** 2 + y + z / 100

study = optuna.create_study()
study.optimize(objective, n_trials=200)

optuna.visualization.plot_contour(study).show()
```

![padding](https://user-images.githubusercontent.com/29617239/91145982-39d52c00-e6f1-11ea-8e68-121e7b66577a.png)

2020-08-26 05:24 UTC, HideakiImamura requested changes
Thanks for the PR! I have several comments.

2020-08-26 05:24 UTC, HideakiImamura commented on optuna/visualization/_contour.py
> +        param_values_range[p_name] = (min_value, max_value)
Re-calculating max and min of `values` are not necessary. How about temporarily preserving them?
```suggestion
        max_value = max(values)
        min_value = min(values)
        if _is_log_scale(trials, p_name):
            padding = (math.log10(max_value) - math.log10(min_value)) * padding_ratio
            min_value = math.pow(10, math.log10(min_value) - padding)
            max_value = math.pow(10, math.log10(max_value) + padding)
        else:
            padding = (max_value - min_value) * padding_ratio
            min_value = min_value - padding
            max_value = max_value + padding
        param_values_range[p_name] = (min_value, max_value)
```

2020-08-26 05:24 UTC, HideakiImamura commented on optuna/visualization/_contour.py
> +    param_values_range: dict,
```suggestion
    param_values_range: Dict[str, Tuple[float, float]],
```

We have to additionally import `from typing import Dict`.

2020-08-26 05:24 UTC, HideakiImamura commented on optuna/visualization/_contour.py
> +
Leaving a comment for "padding" is kind for code readers.
```suggestion

# Padding to the plot.
```

2020-08-26 05:24 UTC, HideakiImamura commented on optuna/visualization/_contour.py
> +    param_values_range: dict,
And, how about making this argument's default value `None`? It is more easy to use this function when testing. If this is `None`, then the `param_values_range` is set to be `{}` (empty dictionary).
```suggestion
    param_values_range: Optional[Dict[str, Tuple[float, float]]] = None,
```
In line 163, we need
```python
if param_values_range is None:
    param_values_range = {}
```

2020-08-26 05:24 UTC, HideakiImamura commented on tests/visualization_tests/test_contour.py
> +        trials, params[0], params[1], StudyDirection.MINIMIZE, {}
```suggestion
        trials, params[0], params[1], StudyDirection.MINIMIZE
```

2020-08-26 05:24 UTC, HideakiImamura commented on tests/visualization_tests/test_contour.py
> +        trials, params[0], params[1], StudyDirection.MINIMIZE, {}
```suggestion
        trials, params[0], params[1], StudyDirection.MINIMIZE
```

2020-08-26 10:50 UTC, zchenry commented
@HideakiImamura Thank you for your kind and detailed comments! I totally agree with you and have revised my codes.

2020-08-27 02:25 UTC, HideakiImamura approved these changes
Thanks for your swift actions! LGTM!

2020-08-30 02:19 UTC, hvy approved these changes
This definitely improves the visualization. Thanks a bunch. LGTM!

2020-08-30 02:19 UTC, merged