Add axis order for plot_pareto_front
optuna/optuna pull request #2000
Opened 2020-11-09 07:00 UTC by okdshin

## Motivation

Current `plot_pareto_front` function can not transpose axis.

## Description of the changes

Add `axis_order` argument by which users can handle axis order. It takes a list of index of axes.

2020-11-09 14:07 UTC, crcrpar reviewed
Thank you for the patch you made!

I left some comments that require some cumbersome work, but I think they'd make this patch better. 🙂

2020-11-10 01:50 UTC, okdshin commented on optuna/multi_objective/visualization/_pareto_front.py
> +        _logger.warning("axis_order contains invalid index lower than 0")
OK. I will modify.

2020-11-10 08:57 UTC, crcrpar reviewed
What a quick action. Much appreciated!

Could you add tests for the newly added exceptions though they may be optional?

2020-11-11 07:54 UTC, crcrpar approved these changes
thank you. Looks good to me.

2020-11-19 03:22 UTC, hvy requested changes
The design and the logic looks good to me as well. I left some nits.

2020-11-19 03:22 UTC, hvy commented on optuna/multi_objective/visualization/_pareto_front.py
> +                f"Size of `axis_order` {axis_order}. Expect: 2, Actual: {len(axis_order)}"
Again a detail but we usually place a period.
```suggestion
                f"Size of `axis_order` {axis_order}. Expect: 2, Actual: {len(axis_order)}."
```

2020-11-19 03:22 UTC, hvy commented on optuna/multi_objective/visualization/_pareto_front.py
> +                "higher than 1"
Ditto.
```suggestion
                "higher than 1."
```

2020-11-19 03:22 UTC, hvy commented on optuna/multi_objective/visualization/_pareto_front.py
> +                "lower than 0"
Ditto.
```suggestion
                "lower than 0."
```

2020-11-19 03:22 UTC, hvy commented on optuna/multi_objective/visualization/_pareto_front.py
> +            A list of axis index indicating the order of axis. If :obj:`None` is specified,
Another minor.
```suggestion
            A list of indices indicating the axis order. If :obj:`None` is specified,
```

2020-11-19 03:22 UTC, hvy commented on optuna/multi_objective/visualization/_pareto_front.py
> +                f"Size of `axis_order` {axis_order}. Expect: 3, Actual: {len(axis_order)}"
Ditto.
```suggestion
                f"Size of `axis_order` {axis_order}. Expect: 3, Actual: {len(axis_order)}."
```

2020-11-19 03:22 UTC, hvy commented on optuna/multi_objective/visualization/_pareto_front.py
> +            raise ValueError(f"Elements of given `axis_order` {axis_order} are not unique!")
Ditto.
```suggestion
            raise ValueError(f"Elements of given `axis_order` {axis_order} are not unique!.")
```

2020-11-19 03:22 UTC, hvy commented on optuna/multi_objective/visualization/_pareto_front.py
> +                "higher than 2"
Ditto.
```suggestion
                "higher than 2."
```

2020-11-19 03:22 UTC, hvy commented on optuna/multi_objective/visualization/_pareto_front.py
> +                "lower than 0"
Ditto.
```suggestion
                "lower than 0."
```

2020-11-24 07:49 UTC, okdshin commented on optuna/multi_objective/visualization/_pareto_front.py
> +import numpy as np
OK

2020-11-24 08:14 UTC, hvy approved these changes
Thanks, LGTM!

2020-11-24 08:14 UTC, merged