[WIP] Modify get_param_importance
optuna/optuna pull request #2003
Opened 2020-11-09 09:38 UTC by tohmae

This PR is proposal for avoiding to skip params sometimes.
This PR addresses issue #1856.

2020-11-25 00:51 UTC, hvy commented
Seems like this has been stale for a while. Do you need any help in proceeding with it? 

By the way, I am wondering if it's not enough to alter the logic in `_get_distributions` to address this issue.

2020-12-07 15:06 UTC, tohmae commented
I am sorry I am late. I modify source code so that  get_param_importance function cat be passed with params argument and add test code.

2021-02-02 12:56 UTC, hvy commented
Sorry, I probably just missed this it but are you changes ready for review? 

Also, it'd be good if you could merge the latest master. We recently introduced RDB test requirements into our CI.

2021-02-08 15:56 UTC, tohmae commented
I merged the latest master. I would be grateful if you could review.

2021-02-08 16:37 UTC, hvy commented
Great, thanks for the updates and the heads up. I'll have a look at it later today!

2021-02-09 12:58 UTC, hvy commented
The `TYPE_CHECKING` changes, they seem unrelated at first. Do you think we should keep them? I would otherwise like to keep the PR minimal. What do you think?

2021-02-09 13:18 UTC, hvy reviewed
Thanks for the great update. I left some comments. Could you have a look at them when you have time?

2021-02-09 13:18 UTC, hvy commented on tests/importance_tests/test_init.py
> +    )
An optional but it might be easier to create a set out of the keys and compare for equality.

2021-02-09 13:18 UTC, hvy commented on optuna/importance/_base.py
> +def _get_distributions(study: "Study", params: Optional[List[str]]) -> Dict[str, BaseDistribution]:
This function is becoming somewhat non-trivial. It's a private one but I'm wondering if we shouldn't write unit tests for it to be certain about keeping its behavior as expected.

2021-02-09 13:18 UTC, hvy commented on optuna/importance/_base.py
> +    for trial in reversed(study._storage.get_all_trials(study._study_id, deepcopy=False)):
You might have reversed the iteration based on `IntersectionSearchSpace` but we don't a cursor here and don't think we can perform any  early breaks. Can we iterate over it in sequence for simplicity?

2021-02-09 13:18 UTC, hvy commented on optuna/importance/_base.py
> +                trial_info_distribution = _get_info_distribution(trial.distributions[param_name])
It feels a bit like over-engineering introducing a dictionary structure here. Actually, can we keep actual distribution objects instead? We could then perhaps keep updating the lows and highs of those objects during the iteration and return them as they are.

2021-02-18 15:00 UTC, tohmae commented
>The TYPE_CHECKING changes, they seem unrelated at first. Do you think we should keep them? I would otherwise like to keep the PR minimal. What do you think?

I do not need intersection_search_space function, so I remove "from optuna.samplers import intersection_search_space" from _base.py. As a result when I import Study, ”ImportError: cannot import name 'Study' from partially initialized module 'optuna.study' (most likely due to a circular import)” message appears. So the TYPE_CHECKING changes. I can not find any other way. Please give me your advice if you have another good idea.

>Thanks for the great update. I left some comments. Could you have a look at them when you have time?

Thank you for your comments. I fixed the parts you pointed out. Could you please review again?

2021-02-27 02:40 UTC, hvy requested changes
Sorry for the delayed review and thanks for the updated. I left some minor comments but it otherwise LGTM!

Might be worth noting that the logic is a bit bug prone when `params` are specified demonstrated by the following test since it puts some assumptions on the caller that it'll exclude all trials that don't include the entire set of params. However, it shouldn't be an issue for now (it's also a private function).

```python
       if param_name == "x1":
            assert distribution.low == 0.1
            if "x4" in params:
                assert distribution.high == 18.0
            else:
                assert distribution.high == 19.0
```

2021-02-27 02:40 UTC, hvy commented on optuna/importance/_base.py
> +                    continue
Before this `continue`, how about asserting that choices are equal? Although it's unlikely to change in the near future, that'd introduce silent bugs.

2021-02-27 02:40 UTC, hvy commented on tests/importance_tests/test_init.py
> +# from optuna.distributions import BaseDistribution
Let's delete the line altogether if the import isn't needed.

2021-02-27 02:40 UTC, hvy commented on tests/importance_tests/test_init.py
> +        #        assert isinstance(distribution, BaseDistribution)
I'm fine with either but let's remove this line or uncomment it.

2021-02-27 02:40 UTC, hvy commented on optuna/importance/__init__.py
> +from typing import TYPE_CHECKING
Let's try avoiding having to rely on `TYPE_CHECKING` to be consistent. (I know you're working on it but leaving a comment for the record 🙇 )

2021-02-27 06:45 UTC, hvy commented on optuna/importance/_base.py
> +                    if trial_param_distribution != param_distribution:
Can we assert this instead since `_get_distributions` is a private method and only used internally?

2021-02-27 08:41 UTC, hvy commented
Thanks, it basically LGTM although I left a single comment. The docs build seems to be failing so we should probably try to fix that as well. I'm not yet sure why that is.

2021-07-07 23:05 UTC, closed without merging