Add mandarin link to ReadTheDocs layout
optuna/optuna pull request #2028
Opened 2020-11-16 12:20 UTC by Crissman

## Motivation
Add a link for the Mandarin documentation to the ReadTheDocs page.

## Description of the changes
Add a link for the Mandarin documentation to the ReadTheDocs page.

2020-11-17 08:43 UTC, toshihikoyanase requested changes
Thank you for your PR. I agree to update the navbar, but I have a comment about the link text and URL.

2020-11-17 08:43 UTC, toshihikoyanase commented on docs/source/_templates/layout.html
> +                </li>
I think we aligned the navbar of `ReadTheDocs` with that of https://optuna.org. How about changing the link text to `Community`?

The nav bar of this PR
![image](https://user-images.githubusercontent.com/3255979/99366215-a4b28f80-28fb-11eb-98c8-a880b3ca6981.png)

The nav bar of https://optuna.org
![image](https://user-images.githubusercontent.com/3255979/99366249-b431d880-28fb-11eb-816e-c9fff3b93816.png)



```suggestion
                <li>
                    <a href="https://optuna.org/#community" class="header_link">Community</a>
                </li>
```

2020-12-09 02:05 UTC, Crissman commented
Agreed and done. 🙇‍♂️

2020-12-10 07:54 UTC, toshihikoyanase commented
@Crissman Thanks! Could you merge the master branch to resolve CI errors?

2020-12-11 01:49 UTC, Crissman commented
Master merged.

2020-12-11 02:21 UTC, toshihikoyanase approved these changes
Thank you for your update. LGTM!

2020-12-11 04:07 UTC, merged