Deprecate `optuna.type_checking` module.
optuna/optuna pull request #2032
Opened 2020-11-17 06:08 UTC by c-bata

## Motivation

To close #1067.

## Description of the changes

Deprecate `optuna.type_checking` module.

2020-11-17 07:00 UTC, hvy requested changes
Thank you for the PR! I left some comments but it otherwise LGTM.

2020-11-17 07:07 UTC, c-bata commented on optuna/__init__.py
> -from optuna.type_checking import TYPE_CHECKING  # NOQA
I directly import `typing.TYPE_CHECKING` at L4. So seems not to break the user code. What do you think?

2020-11-17 07:16 UTC, hvy commented on optuna/__init__.py
> -from optuna.type_checking import TYPE_CHECKING  # NOQA
Ah, that case is fine but I meant something like the following.
```python
import optuna
if optuna.type_checking.TYPE_CHECKING: ...
```

2020-11-17 07:22 UTC, c-bata commented on optuna/__init__.py
> -from optuna.type_checking import TYPE_CHECKING  # NOQA
Ah, I see! I pushed baf3baf9. Thank you for your review!

2020-11-17 07:27 UTC, hvy approved these changes
LGTM! Thanks for your quick fixes.

I noticed we didn't put the version of removal in the message but I guess we can follow it up if deemed necessary. Current changes are at least consistent with `optuna.structs`.

2020-11-17 09:28 UTC, hvy commented
Sorry could you fix the conflict?

2020-11-18 11:34 UTC, c-bata commented on optuna/__init__.py
> +from typing import TYPE_CHECKING  # NOQA
Right! And now `__all__` is defined at https://github.com/optuna/optuna/pull/2013. So we can obviously remove noqa comment.
Thank you for your review!

2020-11-19 11:34 UTC, himkt commented
Thank you for the quick update, LGTM! 😸

2020-11-19 11:34 UTC, himkt approved these changes

2020-11-19 11:34 UTC, merged