Pytorch-Lightning exapmle simplification
optuna/optuna pull request #2294
Opened 2021-02-01 14:02 UTC by TezRomacH

## Motivation

You can remove one extra class `MetricsCallback` in examples. Pytorch-Lightning itself saves metrics states in `trainer.callback_metrics`.

## Description of the changes

I used the native PL functions to achieve the same result.

2021-02-01 14:06 UTC, TezRomacH commented
Mypy check crashes on files that I didn't even change 🤔

2021-02-01 14:57 UTC, nzw0301 commented
I think you need to add a type for ` **kwargs`:  `**kwargs: Any`.

2021-02-01 15:03 UTC, TezRomacH commented
Didn't work :( 

<img width="1139" alt="Screenshot 2021-02-01 at 18 02 50" src="https://user-images.githubusercontent.com/7549587/106476089-b695de80-64b7-11eb-978e-077cb9527c74.png">

2021-02-01 15:16 UTC, nzw0301 commented
Thank you for your reply. On my local machine, it works... Could you push your update?  I think your `mypy` errors do not contain pytorch-lightning's error anymore.

2021-02-01 16:01 UTC, HideakiImamura commented
@TezRomacH What is a version of `mypy`? Currently, we fix the version of `mypy` to `0.790` in `setup.py`. Please use `mypy=0.790`.

2021-02-02 02:13 UTC, HideakiImamura commented
CI is failing with unnatural error.... I think there is nothing wrong with the PR change, so I will re-run it.

2021-02-02 02:26 UTC, HideakiImamura reviewed
Thanks for the PR. I have a comment about `**kwargs`. Please take a look.

2021-02-02 02:26 UTC, HideakiImamura commented on optuna/integration/pytorch_lightning.py
> +        **kwargs: Additional kwargs for ``pytorch_lightning.callbacks.EarlyStopping``
IMO, this `**kwargs` is ambiguous. In Optuna, we have no this type of arguments of classes. How about adding each argument of the superclass if you need it. Which arguments do you want to add?

2021-02-03 12:37 UTC, TezRomacH commented
Hi, guys! What's next? :)

2021-02-03 12:47 UTC, nzw0301 requested changes

2021-02-03 12:47 UTC, nzw0301 commented on optuna/integration/pytorch_lightning.py
> +            monitored has stopped increasing.
Could you add the default value?

2021-02-03 13:08 UTC, TezRomacH commented on optuna/integration/pytorch_lightning.py
> +            monitored has stopped increasing.
```suggestion
            monitored has stopped increasing. Default: ``min``.
```

2021-02-03 13:09 UTC, TezRomacH commented on optuna/integration/pytorch_lightning.py
> +            monitored has stopped increasing.
Done :)

2021-02-03 13:09 UTC, nzw0301 approved these changes
Awesome!

2021-02-03 13:12 UTC, nzw0301 commented
@HideakiImamura Could you take a look this PR?

2021-02-05 08:49 UTC, TezRomacH commented
👀

2021-02-05 09:55 UTC, HideakiImamura reviewed
Sorry for the late reviews. I have a comment. PTAL.

2021-02-05 09:56 UTC, HideakiImamura commented
Ops. My review comment disappeared. Let me rewrite it.

2021-02-05 10:02 UTC, HideakiImamura commented on optuna/integration/pytorch_lightning.py
> +            not found in the validation metrics. Default: ``True``.
In the original [`pytorch_lightning.callbacks.EarlyStopping`](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/early_stopping.py), the stopping rule at the end of validation is Pytorch Lightning's own. However, in this `optuna.integration.PyTorchLightningPruningCallback`, the stopping rule is Optuna's own, which is specified by the pruner object in the `optuna.pruners` module. The stopping rule is implemented in `EarlyStopping.on_validation_end`, but it is overwritten in `PyTorchLightningPruningCallback`.

On the other hand, the stopping rule at the end of epochs is implemented in `EarlyStopping` but isn't in `PytorchLightningPruningCallback`. So, the same rule is applied to both of them. However, IMO, the `PytorchLightningPruningCallback` is designed to use Optuna's pruning feature in PyTorch Lightning, so we should not use it for other purposes. I think if we want to perform the early stopping at the end of epochs, we should define another callback as follows.
```python
callbacks = [
    PyTorchLightningPruningCallback(trial, monitor="val_acc"),
    pl.callbacks.EarlyStopping(monitor="val_acc", mode="max"),
]
```

Therefore, I think we should not add these parameters to `PyTorchLightningPruningCallback`.

2021-02-05 10:02 UTC, HideakiImamura commented
PTAL.

2021-02-05 10:04 UTC, HideakiImamura commented
[Just a note] As a follow-up PR, we may change the inheritance of `PyTorchLightningPruningCallback`. If anything, it might be better to inherit its parent class, the abstract class `Callback`, rather than `EarlyStopping`. Wed need a further investigation about this.

2021-02-05 10:09 UTC, TezRomacH commented
Okay, I agree that EarlyStopping does slightly different things. Let's not inherit from it then, shall we? :)

2021-02-05 10:10 UTC, TezRomacH commented
Let me change the inheritance to Callback in this PR?

2021-02-05 10:33 UTC, HideakiImamura commented
I think that one PR should do one thing. We need to investigate if we really want to change the inheritance, and since that task will be done separately as a follow-up, why not just use `trainer.callback_metrics`, which is what we originally wanted to do in this PR?

2021-02-05 11:00 UTC, TezRomacH commented
Agreed

2021-02-05 11:19 UTC, TezRomacH commented
Removed everything that doesn't apply to the example. I will create an issue to discuss inheritance.

2021-02-05 11:27 UTC, HideakiImamura approved these changes
Thanks for your swift actions! LGTM!

I will participate in the discussion on whether we should change the inheritance of `PyTorchLightningPruningCallbacl`. Thanks for raising an issue too!

2021-02-05 11:28 UTC, HideakiImamura commented
Let me slightly change the title of this PR to represent the content of the PR explicitly.

2021-02-05 11:31 UTC, merged