Example folders
optuna/optuna pull request #2302
Opened 2021-02-03 01:14 UTC by Crissman

## Motivation
Responding to issue #1238.

## Description of the changes
Create folders for each platform that has more than one example to reduce the number of files in the examples folder.

Note, on Merge, optuna.org and Medium posts that reference these examples should be changed.

More updating of URLs will be necessary with this PR. Posting first as WIP to confirm ok to make the directory changes.

2021-02-03 01:51 UTC, HideakiImamura commented
@toshihikoyanase Could you review this PR if you have time?

2021-02-03 02:47 UTC, toshihikoyanase commented
Sure!

2021-02-05 05:32 UTC, Crissman commented
@toshihikoyanase @HideakiImamura 🙇‍♂️

2021-02-08 13:44 UTC, HideakiImamura reviewed
Thanks for the update. I have several comments. Could you take a look?

I've noticed the following points should be changed.
- `optuna/integration/_lightgbm_tuner/__init__.py:L19`
- `optuna/integration/tensorflow.py:L18`

2021-02-08 13:44 UTC, HideakiImamura commented on examples/README.md
>  * [Keras](./keras_simple.py)
```suggestion
* [Keras](./keras/keras_simple.py)
```

2021-02-08 13:44 UTC, HideakiImamura commented on examples/pytorch/pytorch_lightning_simple.py
> +"""
Should we remove `examples/pytorch_lightning_simple.py`?

2021-02-08 13:44 UTC, HideakiImamura commented on examples/README.md
> +* [Scikit-learn](./sklearn/sklearn_simple.py)
The `OptunaSearchCV` used in `examples/optuna_search_cv_simple.py` is the integration module with `scikit-learn`. How about placing it into `examples/sklearn` and adding here?

2021-02-09 05:47 UTC, Crissman commented
Thanks for the catches, @HideakiImamura . Implemented! 🙇‍♂️

2021-02-09 08:25 UTC, toshihikoyanase requested changes
Thank you for your PR. I found some wrong links. Please take a look.

2021-02-09 08:25 UTC, toshihikoyanase commented on optuna/integration/_lightgbm_tuner/__init__.py
> +    ligthgbm/lig htgbm_tuner_simple.py>`_ which optimizes the validation log loss of cancer
Could you fix the path?
```suggestion
    lightgbm/lightgbm_tuner_simple.py>`_ which optimizes the validation log loss of cancer
```

2021-02-09 08:25 UTC, toshihikoyanase commented on optuna/integration/tensorflow.py
> +    tensorflow/tensorflow/tensorflow_estimator_integration.py>`_
ditto.
```suggestion
    tensorflow/tensorflow_estimator_integration.py>`_
```

2021-02-09 08:25 UTC, toshihikoyanase commented on optuna/pruners/_successive_halving.py
> +    <https://github.com/optuna/optuna/tree/c5777b3e/examples/simple_pruning.py#L31>`_,
This URL specifies the commit id, so please leave it as it is. Or, we can replace it with the master branch as follows:
```suggestion
    <https://github.com/optuna/optuna/blob/master/examples/simple_pruning.py#L31>`_,
```

2021-02-09 08:25 UTC, toshihikoyanase commented on optuna/pruners/_successive_halving.py
> +    <https://github.com/optuna/optuna/tree/c5777b3e/examples/chainer/chainer_integration.py#L65>`_).
ditto.
```suggestion
    <https://github.com/optuna/optuna/blob/master/examples/chainer/chainer_integration.py#L65>`_).
```

2021-02-09 18:12 UTC, HideakiImamura commented on examples/README.md
> +* [Scikit-learn](./sklearn/sklearn_simple.py)
The name of class is `OptunaSearchCV`, so how about naming the `sklearn_optuna_search_cv_simple.py`? In addition, how about adding the file to this line.

2021-02-10 01:31 UTC, Crissman commented
I'm impressed with both of your meticulous checks. 🙇  Thanks!

2021-02-15 11:57 UTC, HideakiImamura commented
@Crissman Thanks for the update! Almost LGTM, but you may miss this https://github.com/optuna/optuna/pull/2302#discussion_r573119688.

2021-02-16 05:22 UTC, HideakiImamura approved these changes
LGTM.

2021-02-16 06:43 UTC, toshihikoyanase commented on examples/pytorch/pytorch_lightning_simple.py
> +from pytorch_lightning import Callback
I think you revert the changes in #2294. Could you remove the changes in this file?

2021-02-16 07:44 UTC, toshihikoyanase approved these changes
Thank you for your swift action. LGTM!

2021-02-16 07:44 UTC, merged