"plot_pareto_front" improvement
optuna/optuna pull request #2355
Opened 2021-02-16 09:03 UTC by 0x41head

## Motivation

Refer to #2203 

## Description of the changes

- aligning the color with optuna.visualization.plot_optimization_history, such that the red/blue colors represent the best points or any other points in a consistent way

- including a legend, again, similar to optuna.visualization.plot_optimization_history

2021-02-16 10:42 UTC, hvy commented
Thanks, the changes basically LGTM but could you fix the unit tests that are now failing due to this change? https://github.com/optuna/optuna/pull/2355/checks?check_run_id=1909294510

Also, this is a detail but I'm wondering if you know if we can use the exact same blue and red variations.
- https://66150-122299416-gh.circle-artifacts.com/0/docs/build/html/reference/visualization/generated/optuna.visualization.plot_pareto_front.html#optuna.visualization.plot_pareto_front
- https://66150-122299416-gh.circle-artifacts.com/0/docs/build/html/reference/visualization/generated/optuna.visualization.plot_optimization_history.html#optuna.visualization.plot_optimization_history

2021-02-16 11:22 UTC, 0x41head commented
Do you mean the red line that comes between the markers in `optuna.visualization.plot_optimization_history` ?

2021-02-16 11:25 UTC, hvy commented
Sorry for my poor explanation. I meant that the blue color in the Pareto front plot and the blue color in the optimization history have seemingly different RGB values. Similarly the red color.

2021-02-16 11:42 UTC, 0x41head commented
@hvy  Changed the rgb values of the markers to match `optuna.visualization.plot_optimization_history`
Reference picture : 
![image](https://user-images.githubusercontent.com/53595853/108058474-1aa0d100-707a-11eb-98e3-2b4c03a5ef4d.png)

2021-02-17 00:48 UTC, hvy requested changes

2021-02-17 00:48 UTC, hvy commented on tests/visualization_tests/test_pareto_front.py
> +    print(figure.data)
Ops, debug print left.
```suggestion
```

2021-02-17 05:28 UTC, 0x41head commented on tests/visualization_tests/test_pareto_front.py
> +    print(figure.data)
Thanks for pointing it out .

2021-02-17 05:31 UTC, hvy approved these changes
Thanks for your quick action as always, changes LGTM!

2021-02-18 02:20 UTC, HideakiImamura approved these changes
Thanks for the PR. LGTM!

2021-02-18 02:20 UTC, merged