Simplify the code to find best values.
optuna/optuna pull request #2394
Opened 2021-02-26 04:01 UTC by c-bata

## Motivation

Simplify the code to find best values.

## Description of the changes

```python
>>> import numpy as np
>>> values = [5, 3, 4, 2, 2, 3, 1]
>>> np.minimum.accumulate(values)
array([5, 3, 3, 2, 2, 2, 1])
>>> 
```

2021-02-28 08:43 UTC, keisuke-umezawa approved these changes
LGTM!

2021-02-28 08:44 UTC, keisuke-umezawa commented
@not522 If you have time, could you look on it?

2021-03-01 08:17 UTC, not522 requested changes
Thank you! It seems `np.minimum.accumulate([t.value for t in trials])` is enough in this case.

2021-03-01 08:17 UTC, not522 commented on optuna/visualization/_optimization_history.py
> +            best_values = list(np.minimum.accumulate([t.value for t in trials]))
```suggestion
            best_values = np.minimum.accumulate([t.value for t in trials])
```

2021-03-01 08:17 UTC, not522 commented on optuna/visualization/_optimization_history.py
> +            best_values = list(np.maximum.accumulate([t.value for t in trials]))
```suggestion
            best_values = np.maximum.accumulate([t.value for t in trials])
```

2021-03-01 08:17 UTC, not522 commented on optuna/visualization/matplotlib/_optimization_history.py
> +        best_values = list(np.minimum.accumulate([t.value for t in trials]))
```suggestion
        best_values = np.minimum.accumulate([t.value for t in trials])
```

2021-03-01 08:17 UTC, not522 commented on optuna/visualization/matplotlib/_optimization_history.py
> +        best_values = list(np.maximum.accumulate([t.value for t in trials]))
```suggestion
        best_values = np.maximum.accumulate([t.value for t in trials])
```

2021-03-01 08:24 UTC, c-bata commented
Thank you! I applied your suggestions.

2021-03-02 08:38 UTC, not522 commented
Basically LGTM. Please update unit test to pass CI.

2021-03-05 16:03 UTC, c-bata commented
Thank you. I fixed test cases.

2021-03-09 01:55 UTC, not522 approved these changes
LGTM!

2021-03-09 02:02 UTC, merged