Add documentation for hyperparameter importance target parameter
optuna/optuna pull request #2551
Opened 2021-03-31 11:19 UTC by Crissman

## Motivation
Hyperparameter importance (HPI) can use a callable function to look at the importance of other parameters, but many users may not be familiar with how to do this.

## Description of the changes
Update the hyperparameter and visualization tutorials to highlight this ability. Likewise, update the docs and error messages for HPI to show the same.

2021-03-31 12:31 UTC, nzw0301 requested changes

2021-03-31 12:31 UTC, nzw0301 commented on optuna/importance/_base.py
> +                    objective, use `target=lambda t: t.value[0]` for the target parameter.
```suggestion
                    objective, use `target=lambda t: t.values[0]` for the target parameter.
```

2021-03-31 12:31 UTC, nzw0301 commented on optuna/importance/_fanova/_evaluator.py
> +                "`target=lambda t: t.value[0]` for the first objective value."
```suggestion
                "`target=lambda t: t.values[0]` for the first objective value."
```

2021-03-31 12:31 UTC, nzw0301 commented on optuna/importance/_mean_decrease_impurity.py
> +                "`target=lambda t: t.value[0]` for the first objective value."
```suggestion
                "`target=lambda t: t.values[0]` for the first objective value."
```

2021-03-31 12:31 UTC, nzw0301 commented on tutorial/20_recipes/002_multi_objective.py
> +    study, target=lambda t: t.value[0], target_name="flops"
```suggestion
    study, target=lambda t: t.values[0], target_name="flops"
```

2021-03-31 12:35 UTC, nzw0301 commented
Thank you for your explanation! I felt the exact same thing for `plot_optimization_history` with multi-objective functions. I leave minor comments and one of them will fix the CI error related to the document.

2021-04-01 12:57 UTC, toshihikoyanase commented
@nzw0301 Could you continue the review, please?

2021-04-01 12:58 UTC, nzw0301 approved these changes
LGTM!

2021-04-01 13:09 UTC, nzw0301 commented
Sorry for my careless review. How about adding the description to the arguments of both `optuna.visualization.plot_param_importances` and `optuna.visualization.matplotlib.plot_param_importances` ?

2021-04-02 06:39 UTC, Crissman commented
Thanks, @nzw0301  Caught a few other places that it should be included. 👍

2021-04-02 09:09 UTC, nzw0301 commented
Thanks for your quick update! 

I have a minor comment about backquote. The current `target=lambda t:  ...` is surrounded by a single backquote on both sides, so the documentation looks 

<img width="871" alt="Screenshot 2021-04-02 at 18 00 57" src="https://user-images.githubusercontent.com/7121753/113400909-88604c80-93dd-11eb-8f47-cc00de504ee8.png">

If we add additonal backquote to each side:

## if we add additional backquoto
<img width="879" alt="Screenshot 2021-04-02 at 18 00 38" src="https://user-images.githubusercontent.com/7121753/113400903-85fdf280-93dd-11eb-9566-830de07c7db1.png">

2021-04-06 00:26 UTC, Crissman commented
Doubled down on quotes.

2021-04-06 03:10 UTC, nzw0301 approved these changes
Thanks!

2021-04-09 01:46 UTC, toshihikoyanase reviewed
Thank you for your PR. I added small comments.

2021-04-09 01:46 UTC, toshihikoyanase commented on optuna/importance/_base.py
> +                the objective values are used. Can also be used for other trial parameters, such as
I found `trial parameters` a bit confusing. Readers might recognize it as `trial.parameters`. How about rephrasing it?
```suggestion
                the objective values are used. Can also be used for other trial attributes, such as
```

2021-04-09 01:46 UTC, toshihikoyanase commented on tutorial/10_key_features/005_visualization.py
> +# Learn which hyperparameters are affecting the trial duration with hyperparameter importance
A nit, but other texts have commas at the end of lines.
```suggestion
# Learn which hyperparameters are affecting the trial duration with hyperparameter importance.
```

2021-04-09 01:46 UTC, toshihikoyanase commented on tutorial/20_recipes/002_multi_objective.py
> +# Learn which hyperparameters are affecting the flops most with hyperparameter importance
ditto.
```suggestion
# Learn which hyperparameters are affecting the flops most with hyperparameter importance.
```

2021-04-15 01:34 UTC, toshihikoyanase approved these changes
Thank you for your update. LGTM!

2021-04-15 01:34 UTC, merged