Introduce speed benchmarks using asv
optuna/optuna pull request #2673
Opened 2021-05-14 03:18 UTC by not522

## Motivation
Benchmarking speed can help us implement speedups and detect slowdowns. This PR introduces benchmarks using [asv](https://asv.readthedocs.io/en/stable/).

## Description of the changes
- Add benchmarks
- Add speed benchmarks in GitHub Actions ([Result](https://github.com/not522/optuna/runs/2563402752))
- Configuration

## Discussion
The Redis benchmark use fakeredis. It may be misleading, but developers easily run benchmarks without setting up a Redis server.

2021-05-14 05:04 UTC, HideakiImamura commented
@toshihikoyanase @c-bata Could you review this PR?

2021-05-14 06:11 UTC, c-bata reviewed
Basically LGTM 👍 

I'm curious about how are we monitoring benchmark results? Are we supposed to prepare a web page like https://pandas.pydata.org/speed/pandas/?

2021-05-14 06:11 UTC, c-bata commented on benchmarks/optimize.py
> +class TimeOptimize:
I'd say naming classes like `XxxSuite` is more common.

https://github.com/scikit-image/scikit-image/tree/main/benchmarks
https://asv.readthedocs.io/en/stable/writing_benchmarks.html

```suggestion
class OptimizeSuite:
```

2021-05-17 03:18 UTC, c-bata approved these changes

2021-05-17 06:33 UTC, not522 commented on .github/workflows/speed-benchmarks.yml
> +        python-version: 3.7
Thank you for your suggestion! I updated to Python 3.9, and it works. https://github.com/not522/optuna/actions/runs/842345303

2021-05-17 06:57 UTC, not522 commented
Currently, we have no concrete plan to deploy the benchmark web page. asv has a cool web interface, but we need to store the benchmark result somewhere.

2021-05-18 01:28 UTC, toshihikoyanase requested changes
Thank you for your PR. The benchmark with `asv` looks great to me.
I added two small comments.

2021-05-18 01:28 UTC, toshihikoyanase commented on benchmarks/optimize.py
> +    param_names = "storage, sampler, n_trials"
According to the following result, the `param_name` was recognized as `s`. Do we need to put a list of strings here?

```suggestion
    param_names = ["storage, sampler, n_trials"]
```
```console
[100.00%] ··· ========================= ============                                                                                                                                                                 s                                                                                                                                                                              ------------------------- ------------                                                                                                                                                       inmemory, random, 1000    344±4ms                                                                                                                                                        inmemory, random, 10000   9.39±0.1s                                                                                                                                                         inmemory, tpe, 1000     6.27±0.2s                                                                                                                                                        inmemory, cmaes, 1000     987±10ms                                                                                                                                                         sqlite, random, 1000     27.4±1s                                                                                                                                                          cache, random, 1000     26.1±0.7s                                                                                                                                                         redis, random, 1000     1.67±0.01m                                                                                                                                                     ========================= ============ 
```

2021-05-18 01:28 UTC, toshihikoyanase commented on benchmarks/optimize.py
> +from typing import cast
Do we need to include the `benchmarks` module into the `optuna` distribution package? If not, could you exclude the `benchmark` directory?

When I built a dist file with `python setup.py sdist` and installed the tar ball, I can import the `benchmarks`. This is due to the sdist file includes the `benchmarks` directory.

2021-05-18 01:51 UTC, not522 commented
Thank you for your suggestions. I updated the PR.

2021-05-18 05:16 UTC, toshihikoyanase approved these changes
Thank you for your update. LGTM!

2021-05-18 05:17 UTC, merged