optuna-examples #11 follow up
optuna/optuna pull request #2689
Opened 2021-05-19 10:53 UTC by hvy

## Motivation

Follow up to https://github.com/optuna/optuna-examples/pull/11. 

## Description of the changes

Add URL to new example.

2021-05-19 10:53 UTC, hvy commented
@Crissman , @c-bata could you review this change?

2021-05-19 13:22 UTC, c-bata approved these changes
LGTM 👍

2021-05-20 01:22 UTC, Crissman approved these changes
LGTM

2021-05-20 01:26 UTC, Crissman requested changes
Actually, I think these two groups should be joined as a generic samplers.

2021-05-20 01:26 UTC, Crissman commented on examples/README.md
>  * [SimulatedAnnealingSampler](https://github.com/optuna/optuna-examples/blob/main/samplers/simulated_annealing_sampler.py)
```suggestion
* [User-defined SimulatedAnnealingSampler](https://github.com/optuna/optuna-examples/blob/main/samplers/simulated_annealing_sampler.py)
```

2021-05-20 01:26 UTC, Crissman commented on examples/README.md
```suggestion
```

2021-05-20 01:32 UTC, hvy commented
I see, I don't have a strong opinion about it but sounds good as well being consistent with the file structure. I'd like to fix the inconsistency with `optuna-examples` in this PR however, could we have that discussion in a separate ticket?

2021-05-20 01:37 UTC, Crissman approved these changes
Will deal with merging samplers example in separate PR.

2021-05-20 01:37 UTC, merged