Replace old example URLs in `optuna.integrations`
optuna/optuna pull request #2700
Opened 2021-05-25 10:22 UTC by nzw0301

## Motivation

A sort of follow-up pull request of https://github.com/optuna/optuna/issues/2654. I found a few URLs are still old. This PR fixes them.

## Description of the changes

Replace old URLs.

2021-05-25 11:57 UTC, toshihikoyanase requested changes
I'm not aware of the broken links. Thank you!

2021-05-25 11:57 UTC, toshihikoyanase commented on optuna/integration/mxnet.py
> +    mxnet/mxnet_simple.py>`__
`mxnet_simple.py` does not use `MXNetPruningCallback`. Please revert the filename.
```suggestion
    mxnet/mxnet_integration.py>`__
```

2021-05-25 11:57 UTC, toshihikoyanase commented on optuna/integration/pytorch_lightning.py
> +    pytorch/pytorch_lightning_simple.py>`__
The link is broken. I guess the branch name is missing.
```suggestion
    main/pytorch/pytorch_lightning_simple.py>`__
```

2021-05-25 12:07 UTC, nzw0301 commented
@toshihikoyanase thank you for your careful check!

2021-05-26 01:26 UTC, HideakiImamura commented
@himkt Could you review this PR?

2021-05-26 04:18 UTC, toshihikoyanase approved these changes
Thank you for your update. LGTM!

2021-05-26 12:49 UTC, himkt approved these changes
Nice catch!

2021-05-26 12:49 UTC, merged