Sorts categorical values on axis that contains only numerical values in visualization.matplotlib.plot_slice
optuna/optuna pull request #2709
Opened 2021-05-29 19:31 UTC by Muktan

## Motivation

The slice plot's axis can be improved (by sorting) when a categorical distribution suggests only int or float values.

## Description of the changes

Now the y axis is sorted if it only contains numerical values. 
Before:
![image](https://user-images.githubusercontent.com/31338369/120082664-d0e86d80-c0e1-11eb-95f2-fbad789639bf.png)

After:
![image](https://user-images.githubusercontent.com/31338369/120082673-df368980-c0e1-11eb-9c11-157688c96fb9.png)

Also, if y contains mix of categorical and the numerical e.g. y = trial.suggest_categorical("y", [1,"2asd","3asd","asd"])
previous and current result remains same as follows:
![image](https://user-images.githubusercontent.com/31338369/120082764-5e2bc200-c0e2-11eb-897a-89ed2605b5a3.png)

2021-05-30 08:37 UTC, nzw0301 approved these changes
@Muktan Thank you for your pull request! It looks great.

2021-05-30 08:45 UTC, nzw0301 commented
How about replacing this part 

```python
    elif _is_numerical(trials, param):
        x_values = [x for x in x_values]
        scale = "numerical"
    elif _is_categorical(trials, param):
        x_values = [str(x) for x in x_values]
        scale = "categorical"
```

with 

```python
    elif not _is_numerical(trials, param):
        x_values = [str(x) for x in x_values]
        scale = "categorical"
```

2021-05-30 08:52 UTC, Muktan commented
Okay, let me try these conditions and if everything is good will create another comit.

2021-05-30 09:38 UTC, nzw0301 requested changes
Thank you for your quick response. I have one minor comment.

2021-05-30 09:38 UTC, nzw0301 commented on optuna/visualization/matplotlib/_slice.py
>  from optuna.visualization.matplotlib._utils import _is_categorical
Could you remove this import since `_is_categorical` is no longer used in this file?

2021-05-30 11:29 UTC, nzw0301 approved these changes
Awesome! Again, thank you for your quick update.

2021-06-01 13:10 UTC, Muktan commented
Hey @nzw0301!
This PR is not merged yet, so is there anything that needs to be done further?

2021-06-01 15:22 UTC, nzw0301 commented
Hi @Muktan, the pull request needs two approvals from dev-members to be merged into the master branch. So please kindly give us time.

2021-06-01 15:27 UTC, Muktan commented
Ok got it, Thank You.

2021-06-02 01:04 UTC, Crissman approved these changes
LGTM. Thanks for another!

2021-06-02 01:04 UTC, merged