Added specific test cases
optuna/optuna pull request #2754
Opened 2021-06-21 06:23 UTC by asquare100

## Motivation
Currently, test cases in `optuna/visualization/matplotlib/*.py` are not enough compared to `optuna/visualization/*.py`. 

## Fixes
[Issue](https://github.com/optuna/optuna/issues/2643)

## Description of the changes
In this PR, I have added some specific test cases to the file `tests/visualization_tests/matplotlib/test_intermediate_plot.py`.
I will be creating another PR to add test cases in other files of `tests/visualization_tests/matplotlib/`

2021-06-22 07:09 UTC, Crissman commented
@keisuke-umezawa Can you take a look at this?

2021-06-23 01:43 UTC, Crissman approved these changes
Thank you for the PR! LGTM.

2021-07-07 07:22 UTC, nzw0301 requested changes
Could you replace `assert not figure.has_data()` with `assert len(figure.get_lines()) == 0`?

2021-07-10 05:44 UTC, keisuke-umezawa commented
cc: @asquare100

2021-07-14 09:35 UTC, nzw0301 approved these changes
Basically, the change looks great to me except for my comment. Since we do not get an update, let me merge this PR. I'll send a follow-up PR later.

2021-07-14 09:39 UTC, nzw0301 commented
Let me rename the PR title with a more informative one.

2021-07-14 09:39 UTC, merged