Improve docs of constant liar
optuna/optuna pull request #2785
Opened 2021-07-06 05:31 UTC by hvy

## Motivation

See below description.

## Description of the changes

Adds a note to the constant liar docs that zombie trials also will be considered.

2021-07-10 05:50 UTC, keisuke-umezawa approved these changes
LGTM!

2021-07-13 02:21 UTC, Crissman requested changes
Thanks for the PR! Left some edits for clarity.

2021-07-13 02:21 UTC, Crissman commented on optuna/samplers/_tpe/sampler.py
> +                Abnormally terminated trials are often in the running state.
```suggestion
                Abnormally terminated trials often leave behind a record with a state of `RUNNING` in the storage.
```

2021-07-13 02:21 UTC, Crissman commented on optuna/samplers/_tpe/sampler.py
> +                Such zombie trials will be penalized and taken into account during optimization.
```suggestion
                Such "zombie" trial parameters will be avoided by the constant liar algorithm during subsequent sampling.
```

2021-07-13 02:21 UTC, Crissman commented on optuna/samplers/_tpe/sampler.py
> +                ``heartbeat_interval`` to automatically fail such zombie trials.
```suggestion
                ``heartbeat_interval`` to change the records for abnormally terminated trials to `FAIL`.
```

2021-07-13 03:53 UTC, hvy commented
@Crissman thanks for the review, I applied your suggestions. PTAL. 🙇

2021-07-13 06:42 UTC, Crissman approved these changes
LGTM.

2021-07-13 06:42 UTC, merged