Added alternative callback function #2844
optuna/optuna pull request #2845
Opened 2021-08-04 18:31 UTC by DeviousLab

## Description of the changes
Added alternative callback function TFKerasPruningCallback to the warning of optuna.integration.KerasPruningCallback #2844. Wasn't sure whether to add it to the end or the start of the message.

2021-08-04 18:43 UTC, DeviousLab commented
Any advice on how to shorten the line down to 99 characters?

2021-08-04 19:01 UTC, nzw0301 commented
How about applying [`formats.sh`](https://github.com/optuna/optuna/blob/master/formats.sh)?

2021-08-05 01:56 UTC, DeviousLab commented
Running the bash file formats.sh also gives me a similar error 
![image](https://user-images.githubusercontent.com/53790060/128278810-6dca3a2b-7bbf-4933-b00a-83a443fd28bc.png)

2021-08-05 06:34 UTC, HideakiImamura approved these changes
LGTM

2021-08-05 08:03 UTC, nzw0301 requested changes
The link in the current warning message to `TFKerasCallback` is broken.

In the warning message, there is an extra space in the URL:
```python
from optuna.integration import KerasPruningCallback

KerasPruningCallback()
1: FutureWarning: KerasPruningCallback has been deprecated in v2.1.0. This feature will be removed in v4.0.0. See https://github.com/optuna/optuna/releases/tag/v2.1.0. Recent Keras release (2.4.0) simply redirects all APIs in the standalone keras package to point to tf.keras. There is now only one Keras: tf.keras. There may be some breaking changes for some workflows by upgrading to keras 2.4.0. Test before upgrading. REF: https://github.com/keras-team/keras/releases/tag/2.4.0. There is an alternative callback function that can be used instead:
`TFKerasPruningCallback <(https://optuna.readthedocs.io/en/stable/reference/    generated/optuna.integration.TFKerasPruningCallback.html)>`_
```

Likewise, [the generated page](https://67666-122299416-gh.circle-artifacts.com/0/docs/build/html/reference/generated/optuna.integration.KerasPruningCallback.html#optuna.integration.KerasPruningCallback) does not link to the correct page.

Thus, I would like to suggest fixing the warning message.

2021-08-05 08:04 UTC, nzw0301 commented on optuna/integration/keras.py
> +    generated/optuna.integration.TFKerasPruningCallback.html)>`_ ",
cc: @HideakiImamura

2021-08-05 11:34 UTC, DeviousLab commented on optuna/integration/keras.py
> +    generated/optuna.integration.TFKerasPruningCallback.html)>`_ ",
I'll wait for HideakiImamura's decision on which suggestion is more appropriate before I commit one.

2021-08-06 08:10 UTC, nzw0301 commented on optuna/integration/keras.py
> +    generated/optuna.integration.TFKerasPruningCallback.html)>`_ ",
I asked him which is better with a private channel and he and I agree that the second one is enough. 

Thus could you replace the line by following the second suggestion? 

```suggestion
    ":class:`~optuna.integration.TFKerasPruningCallback`",
```

2021-08-06 16:26 UTC, nzw0301 approved these changes
Awesome! Thank you for your PR!

2021-08-06 16:26 UTC, merged