Speed up `import optuna`
optuna/optuna pull request #3000
Opened 2021-10-12 05:50 UTC by not522

## Motivation
In the current implementation, `import optuna` slows down by importing libraries. This PR will speed up using lazy import.

```shell
$ time python -c "import optuna"
```

- master

```shell
real	0m2.022s
user	0m1.800s
sys	0m0.757s
```

- PR
```shell
real	0m1.078s
user	0m1.218s
sys	0m0.470s
```

### Profile using [tuna](https://github.com/nschloe/tuna)

```shell
$ python -X importtime <(echo import optuna) 2> import.log
$ tuna import.log
```

- master
![image](https://user-images.githubusercontent.com/1255726/136896837-7b80164e-d9fb-49db-8a8f-70a4f73ac551.png)

- PR
![image](https://user-images.githubusercontent.com/1255726/136897713-53bcd9dd-bbc2-49cc-b606-b0a7564ab038.png)

## Description of the changes
- Move `_LazyImport`
- Lazy importing `optuna.importance`, `optuna.visualization`, `optuna.multi_objective.visualization`, and `optuna.study._dataframe`

2021-10-14 09:09 UTC, Crissman commented
@keisuke-umezawa Can you take a look at this, please?

2021-11-02 09:31 UTC, HideakiImamura commented
@keisuke-umezawa I re-assign the reviewer of this PR since it seems that you have a lot of heavy PRs.

@nzw0301 Could you review this PR if you have time?

2021-11-02 11:00 UTC, nzw0301 commented
@HideakiImamura  Sure. 

@not522 Could you resolve the conflicts?

2021-11-04 15:58 UTC, nzw0301 commented
Thanks! I'll review this PR the next Monday.

2021-11-08 07:04 UTC, toshihikoyanase commented
@nzw0301 Let me review this PR on behalf of you as discussed offline.

2021-11-16 12:36 UTC, toshihikoyanase approved these changes
This PR actually halved the import time of Optuna!

```console
$ time python -c "import optuna"
```
This PR:  `python -c "import optuna"  0.84s user 1.15s system 415% cpu 0.479 total`
master: `python -c "import optuna"  1.33s user 1.24s system 244% cpu 1.050 total`

I tried to find possible side effects, but I couldn't.

- `help(optuna.visualization)` described the expected document
- The CLI command `optuna trials` worked as expected
- The expected error messages were shown when I tried to import the modules that don't exist like `from optuna.visualization import foo`
- I can use the lazy-loaded modules/functions including `study.trials_dataframe()` and `optuna.visualization.plot_optimization_history(study)` on the notebook as expected.

Looks great to me.

2021-11-16 22:58 UTC, not522 commented
Thank you for your careful review. I updated the PR to follow https://github.com/optuna/optuna/commit/f076e86308afd7e968eae8f4bac4df896dc58e76.

2021-11-17 05:48 UTC, Crissman requested changes
Some minor English clarification.

2021-11-17 05:48 UTC, Crissman commented on optuna/_imports.py
> +    This class wraps specified module and lazily import it when they are actually accessed.
```suggestion
    This class wraps the specified modules and lazily imports them only when accessed.
```

2021-11-17 05:48 UTC, Crissman commented on optuna/_imports.py
> +    their dependencies all at once.
```suggestion
    Otherwise, `import optuna` is slowed down by importing all submodules and
    dependencies even if not required.
```

2021-11-17 08:25 UTC, toshihikoyanase commented
https://github.com/optuna/optuna/pull/3103 will resolve the CI failures. Could you rebase the branch?

2021-11-17 09:07 UTC, not522 commented
Thank you. I updated the PR. PTAL.

2021-11-19 07:00 UTC, Crissman approved these changes
LGTM!

2021-11-19 07:00 UTC, merged