docs: updated description for missing samplers and pruners
optuna/optuna pull request #3087
Opened 2021-11-07 15:12 UTC by l-e-e-l-a

## Motivation

This PR fixes #3072 and aims at providing comprehensive lists of samplers/pruners implemented in Optuna for the users. 

## Description of the changes

Updated the description to include the missing :
- samplers: `PartialFixedSampler` and `NSGAIISampler`
- pruners: `PatientPruner` and `PercentilePruner`. 

Further, the description has been updated such that the sampler/pruner class names are in alphabetical order.

2021-11-07 16:29 UTC, nzw0301 commented
Great! Could you apply `black`, ideally, [`formats.sh`](https://github.com/optuna/optuna/blob/master/formats.sh)?

2021-11-07 16:32 UTC, l-e-e-l-a commented
> Great! Could you apply `black`, ideally, by using [`formats.sh`](https://github.com/optuna/optuna/blob/master/formats.sh)?

i went through the contributing guide and ran the `./formats.sh` command.
![image](https://user-images.githubusercontent.com/48513587/140653515-7b1be026-cebb-46d2-902d-3dc1af8e3470.png)

2021-11-07 16:36 UTC, nzw0301 commented
Interesting. maybe due to the difference of libraries version or OS. I try to give a concrete modification to this PR.

2021-11-07 16:42 UTC, nzw0301 commented on tutorial/10_key_features/003_efficient_optimization_algorithms.py
> +#
```suggestion
#
```

2021-11-07 16:42 UTC, nzw0301 commented on tutorial/10_key_features/003_efficient_optimization_algorithms.py
> +#
Could you remove this space?

2021-11-08 05:19 UTC, toshihikoyanase commented
@nzw0301 Could you continue the review, please? I think you can merge this PR with a single approval since it only updates the document.

2021-11-08 06:46 UTC, nzw0301 commented
## Ordering 

How about following the ordering on the documentation rather than alphabetical ordering?
I mean the orders on the following pages:
- https://optuna.readthedocs.io/en/latest/reference/pruners.html
- https://optuna.readthedocs.io/en/latest/reference/samplers.html

2021-11-08 06:52 UTC, nzw0301 requested changes
I've left a few comments. What do you think about it?

2021-11-08 06:52 UTC, nzw0301 commented on tutorial/10_key_features/003_efficient_optimization_algorithms.py
> +- Algorithm to enable Partial Fixed parameters implemented in :class:`optuna.samplers.PartialFixedSampler`
```suggestion
- Algorithm to enable partial fixed parameters implemented in :class:`optuna.samplers.PartialFixedSampler`
```

2021-11-08 06:52 UTC, nzw0301 commented on tutorial/10_key_features/003_efficient_optimization_algorithms.py
> +# - Algorithm to prune specified number of trials implemented in :class:`optuna.pruners.PercentilePruner`
How about using the documentation's words:
```suggestion
# - Algorithm to prune specified percentile of trials implemented in :class:`optuna.pruners.PercentilePruner`
```

2021-11-08 19:33 UTC, masaaldosey commented
> I've left a few comments. What do you think about it?

have made suggested changes :)

2021-11-09 08:59 UTC, nzw0301 approved these changes
Great! Thank you for your contributions!

2021-11-09 09:00 UTC, merged