Add tests for generated plots of ``plot_edf``
optuna/optuna pull request #3188
Opened 2021-12-19 07:48 UTC by makinzm

## Motivation

Add test in matplotlib test ``plot_edf``  of plotly.

## Description of the changes

This test confirms 
- that the values are monotonically non-decreasing and  
- that the values are in [0,1].

2021-12-19 09:18 UTC, toshihikoyanase reviewed
Thank you for your PR. The change basically looks good to me. I added some small comments.

2021-12-19 09:18 UTC, toshihikoyanase commented on tests/visualization_tests/test_edf.py
> +    _validate(data[0]["y"])
The `data` variable is only used in a single line. How about simplifying it as follows?
```suggestion
    _validate(figure.data[0]["y"])
```

2021-12-19 09:18 UTC, toshihikoyanase commented on tests/visualization_tests/test_edf.py
> +        _validate(tmp_data["y"])
ditto. In addition, `tmp_data` may be a bit ambiguous. Can we rename it?
```suggestion
    for points in figure.data:
        _validate(points["y"])
```

2021-12-19 09:18 UTC, toshihikoyanase commented on tests/visualization_tests/test_edf.py
> +        _validate(tmp_data["y"])
ditto.
```suggestion
    for points in figure.data:
        _validate(points["y"])
```

2021-12-19 11:52 UTC, nzw0301 requested changes

2021-12-19 11:52 UTC, nzw0301 commented on tests/visualization_tests/test_edf.py
> +def _validate(y_values: Sequence[float]) -> None:
`_validate` sounds unclearn. how about `_validate_y_values`?
```suggestion
def _validate_y_values(y_values: Sequence[float]) -> None:
```

2021-12-19 11:52 UTC, nzw0301 commented on tests/visualization_tests/test_edf.py
> +    # This line confirms that the values are monotonically non-decreasing.
how about this simplification?
```suggestion
    # Confirms that the values are monotonically non-decreasing.
```

2021-12-19 11:52 UTC, nzw0301 commented on tests/visualization_tests/test_edf.py
> +    # This line confirms that the values are in [0,1].
```suggestion

    # Confirms that the values are in [0,1].
```

2021-12-19 14:02 UTC, makinzm commented
Thank you for your modification.

2021-12-20 12:19 UTC, himkt reviewed
The appearances of `_validate` should be replaced with `_validate_edf_values`. ☝️

2021-12-20 12:19 UTC, himkt commented on tests/visualization_tests/test_edf.py
> +    assert np.all((0 <= np_values) * (np_values <= 1))
`&` is recommended for logical and operation.
🔗 https://numpy.org/doc/stable/reference/generated/numpy.logical_and.html

```suggestion
    assert np.all((0 <= np_values) & (np_values <= 1))
```

2021-12-20 13:04 UTC, nzw0301 commented on tests/visualization_tests/test_edf.py
> +    np_values = np.array(y_values)
```suggestion
    np_values = np.array(edf_values)
```

2021-12-22 07:43 UTC, HideakiImamura reviewed
Thanks for the PR. I have two small comments. Could you take a look?

2021-12-22 07:43 UTC, HideakiImamura commented on tests/visualization_tests/test_edf.py
> +    assert len(data) == 1
For consistency as above.
```suggestion
    _validate_edf_values(figure.data[0]["y"])
    assert len(figure.data) == 1
```

2021-12-22 07:43 UTC, HideakiImamura commented on tests/visualization_tests/test_edf.py
> +    assert len(data) == 1
For consistency as above.
```suggestion   
     _validate_edf_values(figure.data[0]["y"])
    assert len(figure.data) == 1
```

2021-12-22 09:06 UTC, nzw0301 approved these changes
LGTM. Thank you for improving the test!

2021-12-27 06:56 UTC, toshihikoyanase approved these changes
Thank you for your updates. LGTM!

2021-12-27 06:57 UTC, toshihikoyanase commented
@himkt @HideakiImamura This PR got two approvals and can I merge it?

2022-01-04 07:12 UTC, HideakiImamura commented
@toshihikoyanase Thanks for the notification. Yes, I agree with the merge. Let me merge this PR.

2022-01-04 07:12 UTC, merged