Update explanation for metrics of AllenNLPExecutor
optuna/optuna pull request #3253
Opened 2022-01-25 07:10 UTC by himkt

This PR tries to improve the documentation for AllenNLP integration.

2022-01-25 07:12 UTC, himkt commented
@chenghuzi I heard that you find the docs of `metrics` parameter in AllenNLP integration vague and difficult to understand (sorry). I tried to make the explanation more informative... Could you please give me a feedback?

2022-01-26 01:28 UTC, hvy commented
@HideakiImamura could you help reviewing this PR?

2022-01-26 01:31 UTC, hvy requested changes
Thanks, looks like an improvement except I left a small nit.

On a side note, I found it a bit confusing that the text is "Trainer" while the actual link targets "GradientDescentTrainer.train", but this is clear from context to expected users?

2022-01-26 01:31 UTC, hvy commented on optuna/integration/allennlp/_executor.py
> +            returns a dictionary consists of metrics after training.
A grammatical suggestion.
```suggestion
            returns a dictionary containing metrics after training.
```

2022-01-26 02:05 UTC, hvy approved these changes
LGTM!

2022-01-26 02:08 UTC, himkt commented
> I found it a bit confusing that the text is "Trainer" while the actual link targets "GradientDescentTrainer.train", but this is clear from context to expected users?

Thank you for the comment. In AllenNLP, `Trainer` is a base class and `GradientDescentTrainer` is used in most cases. But users with AllenNLP CLI may not be aware of `GradientDescentTrainer` because it is hidden inside `allennlp train` command. At least users may understand AllenNLP train a model using some trainer so I used the term `Trainer`. 💭 But based on your comment, I agree that users may be confusing for that. I'll revise the PR to show `GradientDescentTrainer` in the text. 😸

2022-01-26 03:06 UTC, hvy approved these changes
Thanks, LGTM!

2022-01-28 07:56 UTC, HideakiImamura approved these changes
LGTM.

2022-01-28 07:56 UTC, merged

2022-02-03 18:05 UTC, chenghuzi commented
> @chenghuzi I heard that you find the docs of `metrics` parameter in AllenNLP integration vague and difficult to understand (sorry). I tried to make the explanation more informative... Could you please give me a feedback?

Sorry for the delayed response. The new explanation looks much more clear to me. Thanks!