Add Missing Test Function Related to Matplotlib.
optuna/optuna pull request #3284
Opened 2022-02-02 16:42 UTC by MasahitoKumada

## Motivation

Related to #3226

## Description of the changes

Add missing test functions in tests/visualization_tests/matplotlib_tests/test_parallel_coordinate.py

2022-02-03 02:24 UTC, toshihikoyanase commented
@nzw0301 Could you review this PR, please?

2022-02-03 12:16 UTC, nzw0301 commented
Hi, I'm afraid the CIs are failing due to accessing undefined attributes of matplotlib's figure. I believe that other Matplotlib tests, for example, https://github.com/optuna/optuna/blob/master/tests/visualization_tests/matplotlib_tests/test_slice.py, are helpful to implement missing test cases. Please do not paste Plotly's tests because they are different.

2022-02-07 02:19 UTC, MasahitoKumada commented
Thank you. I will try to fix it.

2022-02-27 01:59 UTC, nzw0301 commented
any update? 🤔

2022-02-27 02:21 UTC, nzw0301 commented
Let me rename the PR title for traceability and the forthcoming release note.

2022-02-28 04:57 UTC, nzw0301 commented
Can I review this PR?

2022-02-28 08:20 UTC, nzw0301 requested changes
I'll add more comments later. But let me leave a few suggestions.

2022-03-07 12:58 UTC, nzw0301 commented on tests/visualization_tests/matplotlib_tests/test_parallel_coordinate.py
> +    ] == [1.0, 2.5]
```suggestion
    axes = figure.get_figure().axes
    assert len(axes) == 2 + 1
    assert axes[1].get_ylabel() == "Objective Value"
    assert axes[1].get_ylim() == (0.0, 2.0)
    assert len(figure.findobj(LineCollection)) == 1
    assert figure.findobj(LineCollection)[0].get_array().tolist()[:-1] == [0.0, 2.0, 1.0]
    assert axes[2].get_ylim() == (1.0, 2.5)
    assert [
        axes[2].get_lines()[0].get_ydata()[0],
        axes[2].get_lines()[0].get_ydata()[-1],
    ] == [1.0, 2.5]
    xticklabels = axes[0].get_xticklabels()
    assert xticklabels[0].get_text() == "Objective Value"
    assert xticklabels[1].get_text() == "param_a"
```

2022-03-08 10:52 UTC, nzw0301 commented on tests/visualization_tests/matplotlib_tests/test_parallel_coordinate.py
> +    fig = figure.get_figure()
```suggestion
    axes = figure.get_figure().axes
    assert len(axes) == 2 + 1
```

2022-03-08 10:52 UTC, nzw0301 commented on tests/visualization_tests/matplotlib_tests/test_parallel_coordinate.py
> +    assert fig.axes[1].get_ylim() == (0.0, 2.0)
```suggestion
    assert axes[1].get_ylabel() == "Objective Value"
    assert axes[1].get_ylim() == (0.0, 2.0)
```

2022-03-08 10:54 UTC, nzw0301 requested changes

2022-03-08 10:54 UTC, nzw0301 commented on tests/visualization_tests/matplotlib_tests/test_parallel_coordinate.py
> +    assert fig.axes[2].get_ylim() == (1.0, 2.5)
```suggestion
    assert axes[2].get_ylim() == (1.0, 2.5)
```

2022-03-08 10:54 UTC, nzw0301 commented on tests/visualization_tests/matplotlib_tests/test_parallel_coordinate.py
> +        fig.axes[2].get_lines()[0].get_ydata()[-1],
```suggestion
        axes[2].get_lines()[0].get_ydata()[0],
        axes[2].get_lines()[0].get_ydata()[-1],
```

2022-03-08 10:54 UTC, nzw0301 commented on tests/visualization_tests/matplotlib_tests/test_parallel_coordinate.py
> +    ] == [1.0, 2.5]
```suggestion
    ] == [1.0, 2.5]
    xticklabels = axes[0].get_xticklabels()
    assert xticklabels[0].get_text() == "Objective Value"
    assert xticklabels[1].get_text() == "param_a"    
```

2022-03-08 10:58 UTC, nzw0301 commented
I'm afraid that I'm not sure that I'm an appropriate person as a reviewer because I've suggested too many changes so far. 

@MasahitoKumada Could you update the rest part yourself? If that is so hard, we are happy to merge this PR once, then @toshihikoyanase  or I will create a follow-up PR of this PR.

2022-03-10 11:15 UTC, nzw0301 commented
I'm afraid that we cannot proceed with this PR as the previous way, for example, https://github.com/optuna/optuna/pull/3266 due to the lack of our time. So let me close this PR, I'll send a PR based on this PR. Thank you for your understanding.

2022-03-10 11:15 UTC, closed without merging