Add note to recommend Python3.8 or later in documentation build with artifacts
optuna/optuna pull request #3312
Opened 2022-02-14 15:26 UTC by himkt

🔗 https://github.com/optuna/optuna/issues/3250

I added the note that suggests Python3.8 or later for building the documentation if a contributor wants to use uploaded artifacts.

2022-02-14 15:28 UTC, himkt commented
@nzw0301 PTAL (I mentioned you before CIs are passed because this PR doesn't change any codebase). :pray:

2022-02-15 10:04 UTC, nzw0301 requested changes

2022-02-15 10:04 UTC, nzw0301 commented on CONTRIBUTING.md
> +The artifacts are serialized with [the protocol version 5](https://docs.python.org/3/library/pickle.html#data-stream-format) so you will see the error with Python 3.7 or older.
```suggestion
The pickle files are serialized with [the protocol version 5](https://docs.python.org/3/library/pickle.html#data-stream-format) so you will see the error with Python 3.7 or older.
```

2022-02-15 10:04 UTC, nzw0301 commented on CONTRIBUTING.md
> +Please use Python3.8 or later if you want to build the documentation with artifacts.
```suggestion
Please use Python 3.8 or later if you build the documentation with artifacts.
```

2022-02-16 00:43 UTC, himkt commented
@toshihikoyanase Please take a look for another review.

2022-02-16 08:22 UTC, toshihikoyanase approved these changes
LGTM. Thank you!

2022-02-16 08:23 UTC, merged