Unify fail_stale_trials in each Storage impl
optuna/optuna pull request #3442
Opened 2022-04-04 11:50 UTC by knshnb

## Motivation

Currently, `fail_stale_trials` method is implemented in each Storage class (almost same functionality).

## Description of the changes

- added `_get_stale_trial_ids` method to `BaseStorage`
- unified `fail_stale_trials` and moved to `optuna/storages/_heartbeat.py`

I'm wondering if I should remove the first underscore of `_get_stale_trial_ids`.

2022-04-05 02:39 UTC, HideakiImamura commented
@not522 Could you review this PR if you have time?

2022-04-05 08:09 UTC, not522 reviewed
Thank you for your PR!
Could you make `fail_stale_trials` of `RDBStorage` and `RedisStorage` deprecated instead of removal? Because they are public methods.
Note: `fail_stale_trials` of `BaseStorage` and `_CachedStorage` are private, therefore they can be removed.

2022-04-06 03:37 UTC, knshnb commented
Thanks for your comment! I reverted them with deprecated messages.

2022-04-06 03:37 UTC, knshnb commented
Thanks for your comment! I reverted them with deprecated messages.

2022-04-06 06:24 UTC, g-votte commented
@knshnb 
Thanks for your PR!

@not522 
I'm a little worried about leaving the unused method with the standard `@deprecated` policy.

- Though both `RDBStorage` and `RedisStorage` are public, we don't assume that the user directly call `fail_stale_trials` as written [here](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.storages.RDBStorage.html#optuna.storages.RDBStorage). Breaking the backward compatibility scarcely affects the library users.
- It would be harmful for maintainability. We'd have to take care of them for years, despite that the bloated storage classes are currently problematic.

> Thank you for your PR!
> Could you make fail_stale_trials of RDBStorage and RedisStorage deprecated instead of removal? Because they are public methods.

2022-04-06 06:37 UTC, g-votte commented
Hmm, since we have a precedent in #3323, we just may want to follow the standard `@deprecated` policy so far. We can just ignore [my previous comment](https://github.com/optuna/optuna/pull/3442#issuecomment-1089868760) at least in this PR, and discuss it later in another issue/PR.

2022-04-06 07:14 UTC, HideakiImamura approved these changes
Thanks for the PR. LGTM.

2022-04-06 08:48 UTC, not522 commented
> I'm wondering if I should remove the first underscore of _get_stale_trial_ids.

That makes sense, but we need more discussion on the storage API design (#2943). I prefer keeping it private in this PR.

2022-04-06 08:51 UTC, not522 requested changes

2022-04-06 08:51 UTC, not522 commented on optuna/storages/_base.py
>          """
Could you add the `Returns` section?

2022-04-07 06:45 UTC, knshnb commented
@not522 Thank you for the comment! PTAL. (Please ignore the merge commits, which I made by mistake...)

2022-04-07 07:59 UTC, not522 approved these changes
LGTM!

2022-04-07 07:59 UTC, merged