Add popsize argument to CmaEsSampler
optuna/optuna pull request #3649
Opened 2022-06-09 11:35 UTC by knshnb

## Motivation

We sometimes need to specify the population size of `CmaEsSampler` for efficient parallelization in [batch optimization](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/009_ask_and_tell.html#batch-optimization) etc., but it is not supported currently.

## Description of the changes

- added `popsize` keyword argument to `CmaEsSampler`
- added test

2022-06-13 05:26 UTC, knshnb commented on optuna/samplers/_cmaes.py
> +            as the initial population size.
When `restart_strategy` is `None`, the population size is constant during the optimization. I thought it is natural and we don't need to mention that much detail, but what do you think? (Cc: @c-bata)

2022-06-13 06:08 UTC, c-bata commented on optuna/samplers/_cmaes.py
> +            as the initial population size.
Thank you for the discussion! I agree with @knshnb. The description looks good to me except for the duplicated space characters.

```suggestion
        popsize:
            A population size of CMA-ES. When setted ``restart_strategy = 'ipop'``, this is used
            as the initial population size.
```

2022-06-13 06:17 UTC, nzw0301 commented on optuna/samplers/_cmaes.py
> +            as the initial population size.
Thank you for your explanation and confirmation! The current explanation makes sense.

2022-06-13 06:23 UTC, nzw0301 requested changes
The logic and test look great to me. I have one minor suggestion on the docstring.

By the way, should we mention `popsize` from [the batch optimisation section of the ask-and-tell's tutorial page](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/009_ask_and_tell.html#batch-optimization) if this change improves the performance under the setting?

2022-06-13 06:23 UTC, nzw0301 commented on optuna/samplers/_cmaes.py
> +            A population size of CMA-ES.  When setted ``restart_strategy = 'ipop'``, this is used
minor typo: 

```suggestion
            A population size of CMA-ES. When set ``restart_strategy = 'ipop'``, this is used
```

Removing one space from the double spaces is also pointed out by @c-bata, but let me include it in this comment for the sake of completeness.

2022-06-13 10:23 UTC, c-bata commented
According to the result of my benchmark script, CmaEsSampler seemingly does not work sufficiently even if we set `popsize = n_batch`.
https://gist.github.com/c-bata/c8e800f4958724a50c191cae96a8eecb

I will investigate the cause of performance degradation at a later date :bow:

2022-06-13 23:12 UTC, c-bata commented
Looks good to me except for the docstring of `popsize` parameter 👍

2022-06-14 10:13 UTC, nzw0301 approved these changes
LGTM! 

@c-bata thank you for numerically confirming the improvement by this PR.

2022-06-14 10:20 UTC, knshnb commented
Thank you for the reviews and running benchmarks!
I created an issue (https://github.com/optuna/optuna/issues/3669) related to the points @nzw0301 suggested.

2022-06-14 11:19 UTC, c-bata approved these changes
LGTM!

2022-06-14 11:20 UTC, merged