Test: calling `study.tell` from another process
optuna/optuna pull request #4039
Opened 2022-10-04 19:27 UTC by Abelarm

Added a test for checking the support of `study.tell` being called from another process 

## Motivation
Requested in #4027 

## Description of the changes
Added a new test for calling the `study.tell` from another process, in this case the other process was the `cli` option of optuna, tried to replicate part of the test `test_tell` from `test_cli.py`

2022-10-05 03:09 UTC, HideakiImamura commented
@knshnb @contramundum53 Could you review this PR?

2022-10-06 00:16 UTC, not522 commented
Could you test the `Study.tell` method instead of the command line interface?

2022-10-08 11:29 UTC, Abelarm commented
> Could you test the `Study.tell` method instead of the command line interface?

Yes sure I will!

2022-10-12 19:03 UTC, Abelarm commented
@not522 Did it! Is this more or less what you were looking for?

2022-10-14 03:14 UTC, not522 commented
Thank you for your update! It matches my motivation. In addition, could you add a test for `tell` with the trial number?

2022-10-19 17:45 UTC, Abelarm commented on tests/study_tests/test_study.py
> +            assert True
That's definitely a nicer way to do it, thank you

2022-10-20 01:26 UTC, knshnb approved these changes
Thanks for the update! LGTM.
@not522 Could you take a brief look if you have time? (because the content has been changed since @contramundum53 approved)

2022-10-20 02:03 UTC, not522 reviewed
Thank you for the update! It's almost LGTM. I suggest cosmetic changes.

2022-10-20 03:32 UTC, knshnb commented on tests/study_tests/test_study.py
> +def test_study_tell_process() -> None:
```suggestion
def test_tell_from_another_process() -> None:
```
A nit.

2022-10-24 01:30 UTC, contramundum53 approved these changes
LGTM.

2022-10-24 06:19 UTC, not522 requested changes
LGTM. Could you resolve conflicts?

2022-11-01 04:46 UTC, not522 approved these changes

2022-11-04 04:08 UTC, knshnb commented
@not522 Thanks for resolving the conflict.
@Abelarm Thank you for the contribution to Optuna! Let me merge this PR.

2022-11-04 04:09 UTC, merged