Update actions/cache@v2 -> v3
optuna/optuna pull request #4207
Opened 2022-11-25 07:59 UTC by Alnusjaponica

Motivation
Resolve a part of https://github.com/optuna/optuna/issues/4165.

Description of the changes
update action/cache@v2 -> v3 in all workflow.

2022-12-19 05:58 UTC, toshihikoyanase commented
@Alnusjaponica Could you revert the change in mac-tests? We need to fix it before updating the `actions/cache@v2`.

2022-12-22 08:11 UTC, toshihikoyanase requested changes

2022-12-22 08:11 UTC, toshihikoyanase commented on .github/workflows/mac-tests.yml
> +      uses: actions/cache@v3
See https://github.com/optuna/optuna/pull/4207#issuecomment-1357135697
```suggestion
      uses: actions/cache@v2
```

2022-12-22 08:11 UTC, toshihikoyanase commented on .github/workflows/mac-tests.yml
> +      uses: actions/cache@v3
See https://github.com/optuna/optuna/pull/4207#issuecomment-1357135697
```suggestion
      uses: actions/cache@v2
```

2022-12-23 01:40 UTC, Alnusjaponica commented
Thank you for the review and suggestion. I updated the description and made the PR ready for review.

2022-12-23 01:54 UTC, toshihikoyanase approved these changes
Thank you for your update. LGTM!

[Notes]
> v3.0.0: Updated minimum runner version support from node 12 to node 16.

I confirmed that all CI jobs worked.

> Allowing users to provide a custom timeout as input for aborting download of a cache segment using an environment variable SEGMENT_DOWNLOAD_TIMEOUT_MINS. Default is 60 minutes.

I think the default value (60 minutes) is enough since the most of CI jobs finish in 30 minutes or so.

2022-12-23 10:00 UTC, toshihikoyanase commented
Let me merge this PR with a single approval since it only changes CI.

2022-12-23 10:00 UTC, merged