Output installed packages in all remaining CIs
optuna/optuna pull request #4445
Opened 2023-02-20 15:31 UTC by Kaushik-Iyer

## Motivation
When debugging CI fails, the installed package versions are important information. This PR makes it easy to check them.
This PR changes all of the remaining CIs

## Description of the changes
Add pip freeze in Tests CI

2023-02-21 04:58 UTC, Alnusjaponica reviewed
You should add `Output installed packages` to job `docktest` in `sphinx-build.yml`

2023-02-21 05:46 UTC, Alnusjaponica commented on .github/workflows/dockerimage.yml
> +        pip freeze --all
This command doesn't run in the container. I think replacing 
```
pip freeze --all
```
with
```
docker run "${HUB_TAG}" sh -c "pip freeze --all"
```
would be one of the possible way to see the dependency in the container.

2023-02-21 06:11 UTC, Kaushik-Iyer commented
Made the changes

2023-02-21 08:40 UTC, gen740 requested changes
I realized there are unnecessary trailing spaces before/after changed lines. Could you remove these trailing spaces?

(A lot of yaml files already had these trailing spaces too ...)

2023-02-21 13:31 UTC, Kaushik-Iyer commented
![image](https://user-images.githubusercontent.com/84177184/220358071-f3637375-680b-4d53-a620-56e148393074.png)

I can't find any such spaces in the workflows directory through that command

2023-02-21 13:53 UTC, gen740 commented
Hmmm, that's weird. Is your os Windows?

On my computer, that command tells me trailing spaces.

<img width="875" alt="Screenshot 2023-02-21 at 10 49 55 PM" src="https://user-images.githubusercontent.com/54583542/220364046-a934ae2a-5184-46b4-addc-6d444f8f550d.png">

2023-02-21 18:49 UTC, Kaushik-Iyer commented
![image](https://user-images.githubusercontent.com/84177184/220432820-8fc6568f-10d6-48e8-95d4-b2e68dcdf979.png)

In my linux I am getting a similar output. How do I remove these trailing spaces? Do these refer to the one extra blank line that I have added after my code?

2023-02-22 04:41 UTC, gen740 commented
Use `sed` command to replace all trailing spaces. `ls | xargs -n 1 sed -i "" -E "s/^ +$//"`

2023-02-22 13:48 UTC, Alnusjaponica reviewed
I think you need to add another `Output installed packages` in `performance-benchmarks-bayesmark.yml` for job `report`.

2023-02-22 13:52 UTC, Alnusjaponica reviewed
I think you need to add another `Output installed packages` to the job `report` in `performance-benchmarks-bayesmark.yml`. Currently, you only added `Output installed packages` to the job `benchmarks`.

2023-02-22 14:02 UTC, Kaushik-Iyer commented
@Alnusjaponica I have made the changes

2023-02-22 14:09 UTC, Alnusjaponica commented
@Kaushik-Iyer Thank you for your response. I confirmed the changes.

2023-02-28 07:35 UTC, gen740 commented
@Kaushik-Iyer a friendly reminder :)

2023-02-28 07:45 UTC, Kaushik-Iyer commented
Oh I'm so sorry, I was waiting for a reply and I didn't notice the thumbs up react, I'll make the PR today

2023-02-28 16:10 UTC, Kaushik-Iyer commented
I have pushed the changes

2023-03-01 01:02 UTC, Alnusjaponica approved these changes
LGTM

2023-03-01 11:46 UTC, Alnusjaponica approved these changes

2023-03-01 12:11 UTC, gen740 approved these changes
LGTM!

2023-03-02 01:07 UTC, toshihikoyanase approved these changes
Let me merge this PR since it got two approvals. Thank you for your contribution.

2023-03-02 01:07 UTC, merged