Change arguments of `BaseErrorEvaluator` and classes that inherit from it
optuna/optuna pull request #4607
Opened 2023-04-13 07:26 UTC by cross32768

## Motivation
Current `BaseErrorEvaluator` and classes that inherit from it requires `study` for `evaluate` method.
However, the implementation of `evaluate` method does not require `study`, thus we can replace it by list of `trials`.
This change gives some merits.
* This change make  `evaluate` of `BaseErrorEvaluator`  have the same interface of `evaluate` of `BaseImprovementEvaluator`
* We can call `evaluate` method with fewer information

## Description of the changes
Change the argument of  `evaluate` of `BaseErrorEvaluator` to `list[FrozenTrial]` and `StudyDirection` from old argument  `Study`.

2023-04-17 01:29 UTC, g-votte requested changes

2023-04-17 09:07 UTC, cross32768 commented on tests/terminator_tests/test_erroreval.py
> +    serror = evaluator.evaluate(study.trials, study.direction)
Thank you for your comment. I updated `test_erroreval.py` to cover `maximize` case. Could you take another look?

2023-04-17 23:53 UTC, g-votte approved these changes
LGTM!

@contramundum53 Please marge after your review.

2023-04-21 04:53 UTC, contramundum53 approved these changes
LGTM

2023-04-21 04:54 UTC, merged