solve issue #4557 - error_score
optuna/optuna pull request #4642
Opened 2023-04-27 05:43 UTC by jckkvs

solve https://github.com/optuna/optuna/issues/4557#issue-1646828230

## Motivation

## Description of the changes

2023-05-08 05:45 UTC, contramundum53 commented
@HideakiImamura Could you review this PR?

2023-05-08 05:51 UTC, contramundum53 commented
@Alnusjaponica Could you review this PR?

2023-05-09 00:48 UTC, HideakiImamura reviewed
Thanks for the PR! Changes looks good to me. By the way, Can we validate the changes in unitetests? It would be great to add a test case.

2023-05-09 09:33 UTC, jckkvs commented
Thank you for reviewing this PR.
I agree to add a test case. However, I am not familiar with the test case method used in optuna, so it takes time.

Is the test case necessary to merge the PR or not?

2023-05-18 04:11 UTC, jckkvs commented
Add tests.

2023-05-18 23:38 UTC, HideakiImamura commented
Sorry for the late. It would be great to add tests in this PR since it makes clear to validate the changes.

2023-05-19 07:34 UTC, jckkvs commented
@HideakiImamura 
Thanks. 
I try to know wht the test failed in python 3.7. Please let me know if you have any insight

2023-05-29 04:16 UTC, HideakiImamura commented
The specific versions of `scikit-learn` does not cause the error reported in #4557. So, you need to fix the test more simpler or skip testing when Python is 3.7. I prefer the former. 

How about creating the dummy estimator which raises an ValueError anytime? It simplifies the test.

2023-05-29 07:43 UTC, jckkvs commented
@HideakiImamura 
Thanks. I will try later.

But..
> How about creating the dummy estimator which raises an ValueError anytime? It simplifies the test.

I don't think that's enough.
As I mentioned in my first comment, it should be a ValueError when all fits of all trials in OptunaSearchcv fail.
On the other hand, we should not raise a ValueError if all fits in a trial fail.


For example, if n_features is 10,
"n_components": should raise ValueError if low=15, high=20, but
If "n_components": low=5, high=20 then n_components between 5 and 10 should not raise an Error.

The dummy estimator you proposed can test the former case, but not the latter.

Of course we could consider a dummy estimator for the latter case, but I doubt that such a complex dummy estimator would outperform sklearn's estimator.

2023-06-08 05:39 UTC, Alnusjaponica reviewed
Sorry for my delayed reply. I added some comment on the suggestion and I hope these helps you.

2023-06-08 05:39 UTC, Alnusjaponica commented on optuna/integration/sklearn.py
> +
nit

```suggestion
```

2023-06-08 05:39 UTC, Alnusjaponica commented on tests/integration_tests/test_sklearn.py
> +
nit

```suggestion
```

2023-06-08 05:39 UTC, Alnusjaponica commented on tests/integration_tests/test_sklearn.py
> +    )
I guess what you want to do is as follows:

```suggestion
        ({"max_depth": distributions.IntDistribution(0, 1)}, False),
        ({"max_depth": distributions.IntDistribution(0, 0)}, True),
    ],
)
@pytest.mark.filterwarnings("ignore::RuntimeWarning")
@pytest.mark.filterwarnings("ignore::UserWarning")
def test_objective_error_score_nan_regression(param_dist: dict, expect: bool) -> None:
    X, y = make_regression(n_samples=100, n_features=10)
    est = DecisionTreeRegressor()
    study = optuna.create_study()
    optuna_search = integration.OptunaSearchCV(
        est,
        param_dist,
        cv=3,
        error_score=np.nan,
        random_state=0,
        study=create_study(sampler=BruteForceSampler(), direction="maximize"),
    )
```

2023-06-08 05:39 UTC, Alnusjaponica commented on tests/integration_tests/test_sklearn.py
>  from optuna import integration
Please remember to import `BruteForceSampler` if you accept the suggestion in `test_objective_error_score_nan_regression`.

```suggestion
from optuna import integration
from optuna.samplers import BruteForceSampler
```

2023-06-08 05:39 UTC, Alnusjaponica commented on optuna/integration/sklearn.py
> +                test_score = np.array([np.nan] * n_splits)
The element of `test_score` should be `self.error_score` if it is not `None`, isn't it?

2023-06-08 05:39 UTC, Alnusjaponica reviewed
Sorry for my delayed reply. I added some comment on the suggestion and I hope these helps you.

2023-06-08 05:39 UTC, Alnusjaponica reviewed
Sorry for my delayed reply. I added some comment on the suggestion and I hope these helps you.

2023-06-09 04:38 UTC, Alnusjaponica commented on optuna/integration/sklearn.py
> +                test_score = np.array([np.nan] * n_splits)
@jckkvs 
You need to consider the case that `self.error_score` is `None`.

2023-06-09 04:53 UTC, Alnusjaponica commented on tests/integration_tests/test_sklearn.py
> +        ({"max_depth": distributions.FloatDistribution(0, 1)}, True),
Are there any reason to use `FloatDistribution`? `IntDistribution(0, 0)` seems enough to cause error in all trials.
BTW, `FloatDistribution` without `step` should be not acceptable for `BruteForceSampler` (see [docs](https://optuna.readthedocs.io/en/stable/reference/samplers/generated/optuna.samplers.BruteForceSampler.html#optuna.samplers.BruteForceSampler:~:text=(objective)-,Note,-The%20defined%20search)), so what this test catch as `ValueError` seem the one from `BruteForceSampler`, not from `OptunaSearchCV`.

2023-06-09 05:01 UTC, Alnusjaponica commented on tests/integration_tests/test_sklearn.py
> +        ({"max_depth": distributions.FloatDistribution(0, 1)}, True),
@HideakiImamura 
Is it better to implement something like `DeterministicSampler` instead of using `BruteForceSampler`?

2023-06-13 03:31 UTC, HideakiImamura commented
@jckkvs Thanks for your work. Since it appears to be very costly at the point of adding unit tests, how about we proceed to add them without unit tests once in this PR, or only add very simple ones, and then add tests as a follow-up by committers (us)?

2023-06-14 04:42 UTC, HideakiImamura commented
@jckkvs Thanks for the reply. So, could you remove the unit-tests which you added in this PR? Sorry for the confusion.

2023-06-14 04:46 UTC, HideakiImamura commented
It would be better to undo all changes in the test file.

2023-06-15 02:33 UTC, Alnusjaponica requested changes

2023-06-15 02:33 UTC, Alnusjaponica commented on optuna/integration/sklearn.py
> +                test_score = np.array([self.error_score] * n_splits)
https://github.com/optuna/optuna/pull/4642#discussion_r1223835320

```suggestion
                test_score = np.array(
                    [self.error_score if self.error_score is not None else np.nan] * n_splits
                )
```

2023-06-15 02:34 UTC, Alnusjaponica commented
Other than the suggestion above, LGTM.

2023-06-15 05:15 UTC, Alnusjaponica approved these changes
LGTM.

2023-06-16 01:57 UTC, HideakiImamura approved these changes
Thank you for the long running! LGTM!

2023-06-16 01:57 UTC, merged