Add cv_results_ to OptunaSearchCV
optuna/optuna pull request #4751
Opened 2023-06-16 07:28 UTC by jckkvs

## Motivation
This is to enhance compatibility with [sklearn.GridSearchCV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html).

The user_attrs is already implemented in Optuna, to obtain the score of each trial, but cv_results_enable to obtain the scores of all trials at once.

In addition,
we can easily calculate the bias_correction proposed by Tibshirani and Tibshirani by cv_results_　(https://tibshirani.su.domains/ftp/AOAS224.pdf).

## Description of the changes

Add cv_results_ to OptunaSearchCV

The variable names  ```cv_results_dict_in_list``` , ```cv_results_list_in_dict``` are very long, so we can change them according to optuna's conventions.

2023-06-23 02:36 UTC, toshihikoyanase requested changes
Thank you for your PR. I'm a bit hesitant about introducing a new method to the `Study` class, as this functionality seems to be specific to `OptunaSearchCV`. Please check the following comment.

2023-06-23 02:36 UTC, toshihikoyanase commented on optuna/study/study.py
> +        return cv_results_list_in_dict
Could you consider moving this implementation to `optuna/integration/sklearn.py`?
`Trial.user_attrs` can hold a variety of data, not just CV results, so the current implementation might be specific to `OptunaSearchCV`.

2023-06-23 02:37 UTC, toshihikoyanase commented
@Alnusjaponica Could you join the review, please?

2023-07-02 23:23 UTC, Alnusjaponica requested changes
@jckkvs You need to test the behavior of `OptunaSearchCV.cv_results_` too.

2023-07-03 02:01 UTC, toshihikoyanase commented on optuna/integration/sklearn.py
> +        """
Sorry for the delayed response. Could you update the docstrings? I don't think this attribute returns all trials (i.e., `list[FrozenTrial]`). In my understanding, it returns a list of CV results corresponding to all the trials.

2023-07-03 07:09 UTC, Alnusjaponica commented on optuna/integration/sklearn.py
> +            for key in cv_results_dict_in_list[0]
Is this safe when `len(cv_results_dict_in_list)==0`?

2023-07-07 08:59 UTC, toshihikoyanase commented on optuna/integration/sklearn.py
> +        """
These lines seem to be duplicated. How about unifying it like the other properties?

```suggestion
        """A dictionary mapping a metric name to a list of Cross-Validation results of all trials."""
```

2023-07-07 09:01 UTC, toshihikoyanase commented on optuna/integration/sklearn.py
> +        """
Thanks!

2023-07-07 09:02 UTC, toshihikoyanase commented on optuna/study/study.py
> +        return cv_results_list_in_dict
> your proposal contains typo

Oops! Sorry for bothering you. Please ignore my comment and overwrite it with your change.

2023-07-19 06:24 UTC, toshihikoyanase approved these changes
I'm sorry for the delayed response. LGTM!
@Alnusjaponica Please merge after your review.

2023-07-21 07:57 UTC, Alnusjaponica approved these changes
Apologies for the delay. LGTM too.
@toshihikoyanase Could you merge this PR?

2023-07-24 05:19 UTC, toshihikoyanase commented
@Alnusjaponica Thank you for your review. Let me merge this PR.

2023-07-24 05:19 UTC, merged