Remove fakeredis version constraint
optuna/optuna pull request #4873
Opened 2023-08-16 06:00 UTC by contramundum53

## Motivation

Fix #3607 .
Currently CI is failing due to old fakeredis.

## Description of the changes
Remove all constraints of fakeredis.

2023-08-16 06:03 UTC, contramundum53 commented
@c-bata Can you review this PR? 
Since the changes are only related to CI, you can merge this PR by one accept.

2023-08-16 06:37 UTC, c-bata commented on .github/workflows/tests-integration.yml
> -        pip install "fakeredis<2.11.1"
I think you can remove a comment in L49.

2023-08-16 06:38 UTC, c-bata requested changes
Thank you for your pull request. I left some minor comments.

2023-08-16 06:38 UTC, c-bata commented on .github/workflows/coverage.yml
> -        pip install "fakeredis<2.11.1"
Could you remove the comment in L45?

2023-08-16 06:38 UTC, c-bata commented on .github/workflows/mac-tests.yml
> -        pip install "fakeredis<2.11.1"
ditto.

2023-08-16 06:38 UTC, c-bata commented on .github/workflows/mac-tests.yml
> -        pip install "fakeredis<2.11.1"
ditto.

2023-08-17 05:53 UTC, c-bata approved these changes
LGTM.

2023-08-17 05:54 UTC, merged