Fix document regarding ArtifactNotFound
optuna/optuna pull request #4982
Opened 2023-09-30 08:20 UTC by smygw72

## Motivation

Some old documents remains (e.g., ":exc:`~optuna_dashboard.artifact.exceptions.ArtifactNotFound` exception"). 

## Description of the changes

Updated the above documents.

2023-09-30 08:31 UTC, toshihikoyanase requested changes
Could you check the module paths, please?

2023-09-30 08:31 UTC, toshihikoyanase commented on optuna/artifacts/_protocol.py
> +        :exc:`~optuna.artifact.exceptions.ArtifactNotFound` exception
A nit.
```suggestion
        :exc:`~optuna.artifacts.exceptions.ArtifactNotFound` exception
```

2023-09-30 08:31 UTC, toshihikoyanase commented on optuna/artifacts/_protocol.py
> +        exist, an :exc:`~optuna.artifact.exceptions.ArtifactNotFound` exception
ditto.
```suggestion
        exist, an :exc:`~optuna.artifacts.exceptions.ArtifactNotFound` exception
```

2023-09-30 08:31 UTC, toshihikoyanase commented on optuna/artifacts/exceptions.py
> +    :meth:`~optuna.artifact.protocol.ArtifactBackend.open_reader` or
Hmm, I'm not sure but ArtifactStore is in a private submodule.
```suggestion
    :meth:`~optuna.artifacts._protocol.ArtifactStore.open_reader` or
```

2023-09-30 08:31 UTC, toshihikoyanase commented on optuna/artifacts/exceptions.py
> +    :meth:`~optuna.artifact.protocol.ArtifactBackend.remove` methods.
```suggestion
    :meth:`~optuna.artifacts._protocol.ArtifactStore.remove` methods.
```

2023-09-30 08:45 UTC, c-bata approved these changes
LGTM

2023-10-03 08:37 UTC, toshihikoyanase approved these changes
LGTM. Thank you!

2023-10-03 08:37 UTC, merged