Remove pytorch integration
optuna/optuna pull request #5213
Opened 2024-01-29 15:31 UTC by nabenabe0928

## Motivation

## Description of the changes

2024-02-05 08:31 UTC, y0z requested changes
I leave some change suggestions.

2024-02-05 08:31 UTC, y0z commented on optuna/integration/pytorch_distributed.py
> +from optuna.integration.pytorch_distributed import TorchDistributedTrial
```suggestion
from optuna_integration.pytorch_distributed import TorchDistributedTrial
```

2024-02-05 08:31 UTC, y0z commented on optuna/integration/pytorch_ignite.py
> +from optuna.integration.pytorch_ignite import PyTorchIgnitePruningHandler
```suggestion
from optuna_integration.pytorch_ignite import PyTorchIgnitePruningHandler
```

2024-02-05 08:31 UTC, y0z commented on optuna/integration/pytorch_lightning.py
> +from optuna.integration.pytorch_lightning import PyTorchLightningPruningCallback
```suggestion
from optuna_integration.pytorch_lightning import PyTorchLightningPruningCallback
```

2024-02-05 08:35 UTC, y0z commented
This PR progresses https://github.com/optuna/optuna/issues/4484.

2024-02-06 06:57 UTC, contramundum53 commented
@nabenabe0928 Could you move [these CI](https://github.com/optuna/optuna/blob/33b4eda9074ab6291612ed251e32acc0e0341f46/.github/workflows/tests-mpi.yml#L81-L84) to optuna_integration?

2024-02-09 04:25 UTC, nabenabe0928 commented
@contramundum53 Could you review this PR?

2024-02-14 06:06 UTC, contramundum53 approved these changes
LGTM!

2024-02-14 06:08 UTC, y0z approved these changes
LGTM

2024-02-14 06:10 UTC, merged