Implement optuna.terminator using optuna._gp
optuna/optuna pull request #5241
Opened 2024-02-09 08:20 UTC by y0z

## Motivation
- Change the GP implementation used in `optuna.terminator` to `optuna._gp` from BoTorch.

## Description of the changes
- Refactoring `optuna.terminator` and related code for using `optuna._gp`.
- Remove files that are no longer needed.

2024-02-09 08:54 UTC, contramundum53 commented
<img width="504" alt="image" src="https://github.com/optuna/optuna/assets/24619922/cb191feb-dea9-4ad7-a06a-d97ec7808206">
The result looks good.

```
import optuna
import numpy as np
from optuna.terminator import RegretBoundEvaluator

study = optuna.study.create_study(sampler=optuna.samplers.TPESampler())

def objective(trial):
    x = trial.suggest_float("x", -3, 3)
    y = trial.suggest_float("y", -3, 3)
    return x ** 2 + y ** 2



study.optimize(objective, n_trials=50)
from optuna.visualization import plot_terminator_improvement

plot_terminator_improvement(study, improvement_evaluator=RegretBoundEvaluator(top_trials_ratio=1.0))
```

2024-02-09 09:22 UTC, contramundum53 approved these changes
LGTM!

2024-02-09 09:25 UTC, contramundum53 commented
@nabenabe0928

2024-02-09 09:27 UTC, contramundum53 commented
Follow-up tasks:
* Use `kernel_params_cache` to speed up evaluation
* Set `DEFAULT_TOP_TRIALS_RATIO` to 1.0
* Set `beta` to constant

2024-02-09 20:54 UTC, nabenabe0928 reviewed
I confirmed that we get the identical result with my modification as well!

```python
import optuna
import numpy as np
from optuna.terminator import RegretBoundEvaluator

study = optuna.study.create_study(sampler=optuna.samplers.TPESampler(seed=42))

def objective(trial):
    x = trial.suggest_float("x", -3, 3)
    y = trial.suggest_float("y", -3, 3)
    return x ** 2 + y ** 2



study.optimize(objective, n_trials=50)
from optuna.visualization import plot_terminator_improvement

plot_terminator_improvement(study, improvement_evaluator=RegretBoundEvaluator(top_trials_ratio=1.0, seed=42))
```

2024-02-09 20:54 UTC, nabenabe0928 commented on optuna/terminator/improvement/evaluator.py
>      def evaluate(
I would code like this to narrow down the variable scopes and enhance the readability.
IMO, the calculation of standardized regret bound should be separated from the main method.

```python
    def _compute_standardized_regret_bound(
        self,
        kernel_params: "gp.KernelParamsTensor",
        gp_search_space: "search_space.SearchSpace",
        normalized_params: np.ndarray,
        standardized_scores: np.ndarray,
    ) -> float:
        """
        In the original paper, f(x) was intended to be minimized, but here we would like to
        maximize f(x), i.e. score_vals. Hence, the following changes happen:
            1. min(ucb) over top trials becomes max(lcb) over top trials, and
            2. min(lcb) over the search space becomes max(ucb) over the search space, and
            3. Regret bound becomes max(ucb) over the search space minus max(lcb) over top trials.
        """
        n_trials, n_params = normalized_params.shape
        sqrt_beta = np.sqrt(_get_beta(n_params=n_params, n_trials=n_trials))
        ucb_acqf_params = acqf.create_acqf_params(
            acqf_type=acqf.AcquisitionFunctionType.UCB,
            kernel_params=kernel_params,
            search_space=gp_search_space,
            X=normalized_params,
            Y=standardized_scores,
            sqrt_beta=sqrt_beta,
        )
        seed = self._rng.rng.randint(np.iinfo(np.int32).max)
        # UCB over the search space. (Original: LCB over the search space. See Change 1 above.)
        max_ucb = np.max(
            acqf.eval_acqf_no_grad(ucb_acqf_params, normalized_params),
            initial=optim.optimize_acqf_sample(ucb_acqf_params, self._optimize_n_samples, seed)[1],
        )
        lcb_acqf_params = acqf.create_acqf_params(
            acqf_type=acqf.AcquisitionFunctionType.UCB,
            kernel_params=kernel_params,
            search_space=gp_search_space,
            X=normalized_params,
            Y=standardized_scores,
            sqrt_beta=-sqrt_beta,
        )
        # LCB over the top trials. (Original: UCB over the top trials. See Change 2 above.)
        max_lcb = np.max(acqf.eval_acqf_no_grad(lcb_acqf_params, normalized_params))
        # max(UCB) - max(LCB). (Original: min(UCB) - min(LCB). See Change 3 above.)
        return max_ucb - max_lcb

    def _get_top_n(
        self, params: np.ndarray, score_vals: np.ndarray
    ) -> tuple[np.ndarray, np.ndarray]:
        assert len(params) == len(score_vals)
        n_trials = len(params)
        top_n = np.clip(int(n_trials * self._top_trials_ratio), self._min_n_trials, n_trials)
        top_n_val = np.partition(score_vals, n_trials - top_n)[n_trials - top_n]
        top_mask = score_vals >= top_n_val
        return params[top_mask], score_vals[top_mask]

    def evaluate(self, trials: List[FrozenTrial], study_direction: StudyDirection) -> float:
        optuna_search_space = intersection_search_space(trials)
        self._validate_input(trials, optuna_search_space)
        complete_trials = [t for t in trials if t.state == TrialState.COMPLETE]

        # _gp module assumes that optimization direction is maximization
        sign = -1 if study_direction == StudyDirection.MINIMIZE else 1
        score_vals = np.array([t.value for t in complete_trials]) * sign
        gp_search_space, normalized_params = search_space.get_search_space_and_normalized_params(
            complete_trials, optuna_search_space
        )

        top_n_normalized_params, top_n_scores = self._get_top_n(normalized_params, score_vals)
        top_n_score_std = max(1e-10, top_n_scores.std())
        top_n_standardized_scores = (top_n_scores - np.mean(top_n_scores)) / top_n_score_std
        kernel_params = gp.fit_kernel_params(
            X=top_n_normalized_params,
            Y=top_n_standardized_scores,
            is_categorical=(gp_search_space.scale_types == search_space.ScaleType.CATEGORICAL),
            log_prior=self._log_prior,
            minimum_noise=self._minimum_noise,
            initial_kernel_params=None,
        )
        standardized_regret = self._compute_standardized_regret_bound(
            kernel_params=kernel_params,
            gp_search_space=gp_search_space,
            normalized_params=top_n_normalized_params,
            standardized_scores=top_n_standardized_scores,
        )
        return standardized_regret * top_n_score_std
```

2024-02-13 01:43 UTC, y0z commented on optuna/terminator/improvement/evaluator.py
> +            sqrt_beta=-sqrt_beta,
> sqrt_beta is supposedly a positive value

You're right. To resolve this, I added LCB.

2024-02-13 01:44 UTC, y0z commented on optuna/terminator/improvement/evaluator.py
> -        gp: Optional[BaseGaussianProcess] = None,
I added the reference.

2024-02-13 05:20 UTC, y0z commented on optuna/terminator/improvement/evaluator.py
> +    beta /= 5
This issue will be resolved in another PR.

2024-02-13 05:26 UTC, nabenabe0928 commented on optuna/terminator/improvement/evaluator.py
> +    beta = 2 * np.log(n_params * n_trials**2 * np.pi**2 / 6 / delta)
```suggestion
    # TODO(nabenabe0928): Check the original implementation to verify.
    # Especially, |D| seems to be the domain size, but not the dimension based on Theorem 1.
    beta = 2 * np.log(n_params * n_trials**2 * np.pi**2 / 6 / delta)
```

2024-02-13 05:26 UTC, nabenabe0928 commented on optuna/terminator/improvement/evaluator.py
> +    - `Automatic termination for hyperparameter optimization <https://proceedings.mlr.press/v188/makarova22a.html>`_
nit

```suggestion
    - `Automatic Termination for Hyperparameter Optimization <https://proceedings.mlr.press/v188/makarova22a.html>`_
```

2024-02-13 05:26 UTC, nabenabe0928 commented on optuna/terminator/improvement/evaluator.py
> +        beta = np.sqrt(_get_beta(n_params, len(normalized_top_n_params)))
It is not `sqrt_beta` anymore.
```suggestion
        beta = _get_beta(n_params, len(normalized_top_n_params))
```

2024-02-13 05:47 UTC, nabenabe0928 commented on optuna/terminator/improvement/evaluator.py
> +        optuna_search_space: Dict[str, BaseDistribution],
We can use `normalized_top_n_params` instead.
```suggestion
```

2024-02-13 05:47 UTC, nabenabe0928 commented on optuna/terminator/improvement/evaluator.py
> +        beta = _get_beta(n_params, len(normalized_top_n_params))
```suggestion
        n_trials, n_params = normalized_top_n_params.shape

        # calculate max_ucb
        beta = _get_beta(n_params, n_trials)
```

2024-02-13 05:47 UTC, nabenabe0928 commented on optuna/terminator/improvement/evaluator.py
> +        )
```suggestion
        seed = self._rng.rng.randint(np.iinfo(np.int32).max)
        # UCB over the search space. (Original: LCB over the search space. See Change 1 above.)
        max_ucb = max(
            acqf.eval_acqf_no_grad(ucb_acqf_params, normalized_top_n_params).max(),
            default=optim.optimize_acqf_sample(ucb_acqf_params, self._optimize_n_samples, seed)[1],
        )
```

2024-02-13 05:47 UTC, nabenabe0928 commented on optuna/terminator/improvement/evaluator.py
> +        )
```suggestion
        max_lcb = np.max(acqf.eval_acqf_no_grad(lcb_acqf_params, normalized_top_n_params))
```

2024-02-13 05:51 UTC, nabenabe0928 commented on optuna/terminator/improvement/evaluator.py
> +            initial_kernel_params=None,
```suggestion
            # TODO(y0z): Add `kernel_params_cache` to speedup.
            initial_kernel_params=None,
```

2024-02-13 08:07 UTC, nabenabe0928 reviewed
Let's add the version constraints to workflow.yml.

2024-02-13 08:07 UTC, nabenabe0928 commented on tests/terminator_tests/test_callback.py
> +
Please 
```suggestion
```

2024-02-13 08:07 UTC, nabenabe0928 commented on tests/terminator_tests/test_erroreval.py
> +
```suggestion

import pytest

```

2024-02-13 08:07 UTC, nabenabe0928 commented on tests/terminator_tests/test_terminator.py
> +
```suggestion
import pytest

```

2024-02-13 08:07 UTC, nabenabe0928 commented on tests/visualization_tests/test_terminator_improvement.py
> +
```suggestion
from typing import Any
from typing import Callable

import pytest

```

2024-02-13 08:46 UTC, nabenabe0928 requested changes
I was missing a bug until now.

2024-02-13 08:46 UTC, nabenabe0928 commented on optuna/_gp/acqf.py
> +        return ucb(mean=mean, var=var, beta=acqf_params.beta)
```suggestion
        return lcb(mean=mean, var=var, beta=acqf_params.beta)
```

2024-02-13 08:50 UTC, y0z commented on optuna/_gp/acqf.py
> +        return ucb(mean=mean, var=var, beta=acqf_params.beta)
Thank you!

2024-02-14 06:13 UTC, contramundum53 approved these changes
LGTM again!

2024-02-14 06:13 UTC, merged