Add a guide to PED-ANOVA for `n_trials>10000`
optuna/optuna pull request #5310
Opened 2024-03-13 11:44 UTC by nabenabe0928

## Motivation

As the information at:
- https://optuna.readthedocs.io/en/stable/reference/importance.html
- https://optuna.readthedocs.io/en/stable/reference/generated/optuna.importance.get_param_importances.html
hits when we google "optuna importance", I added the note about PED-ANOVA.

## Description of the changes

I added a note about PED-ANOVA.

2024-03-13 12:35 UTC, nzw0301 requested changes
Let me leave very minor comments.

2024-03-13 12:35 UTC, nzw0301 commented on docs/source/reference/importance.rst
> +   If `n_trials` is more than 10000, the Cython implementation takes more than a minute, so you can use :class:`~optuna.importance.PedAnovaImportanceEvaluator` instead, enabling the evaluation to fin
```suggestion
   If ``n_trials`` is more than 10000, the Cython implementation takes more than a minute, so you can use :class:`~optuna.importance.PedAnovaImportanceEvaluator` instead, enabling the evaluation to finish in a second.
```

2024-03-13 12:35 UTC, nzw0301 commented on optuna/importance/__init__.py
> +                If `n_trials` is more than 10000, the Cython implementation takes more than
```suggestion
                If ``n_trials`` is more than 10000, the Cython implementation takes more than
```

2024-03-13 12:36 UTC, nabenabe0928 commented
@nzw0301 Thank you for your comments!

2024-03-14 01:50 UTC, nabenabe0928 commented
@HideakiImamura @eukaryo Could you review this PR?

2024-03-14 03:28 UTC, eukaryo approved these changes
LGTM!
fyi: Two modified pages build by CI are following:
https://optuna--5310.org.readthedocs.build/en/5310/reference/importance.html

https://optuna--5310.org.readthedocs.build/en/5310/reference/generated/optuna.importance.get_param_importances.html#optuna.importance.get_param_importances

2024-03-15 02:06 UTC, HideakiImamura approved these changes
LGTM.

2024-03-15 02:06 UTC, merged