Use sphinx rst syntax
optuna/optuna pull request #5345
Opened 2024-03-19 17:05 UTC by nzw0301

## Motivation

## Description of the changes

2024-03-21 01:25 UTC, eukaryo commented
@nabenabe0928 Could you review this PR?

2024-03-21 06:11 UTC, eukaryo approved these changes
LGTM. I checked the following docs:
https://optuna--5345.org.readthedocs.build/en/5345/reference/generated/optuna.pruners.WilcoxonPruner.html#optuna.pruners.WilcoxonPruner
https://optuna--5345.org.readthedocs.build/en/5345/reference/samplers/generated/optuna.samplers.GPSampler.html#optuna.samplers.GPSampler

2024-03-22 08:06 UTC, nabenabe0928 reviewed
I left a minor comment, but LGTM!

2024-03-22 08:06 UTC, nabenabe0928 commented on optuna/pruners/_wilcoxon.py
> +    the historical average of the evaluated values.
```suggestion
    in the same setting, you must provide e.g., the historical average of the evaluated values.
```

2024-03-25 01:58 UTC, nabenabe0928 approved these changes
LGTM!

2024-03-25 02:02 UTC, nabenabe0928 requested changes
I missed one thing!

2024-03-25 02:02 UTC, nabenabe0928 commented on optuna/samplers/_gp/sampler.py
> +        You can install these dependencies with ``pip install scipy pytorch``.
```suggestion
        This sampler requires ``scipy`` and ``torch``.
        You can install these dependencies with ``pip install scipy torch``.
```

2024-03-25 04:21 UTC, nzw0301 commented on optuna/samplers/_gp/sampler.py
> +        You can install these dependencies with ``pip install scipy pytorch``.
Nice🙏

2024-03-25 04:30 UTC, nabenabe0928 approved these changes

2024-03-25 04:36 UTC, merged